# Generated by Django 5.2.1 on 2025-11-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Введіть прізвище та ім'я працівника", max_length=255, verbose_name="Прізвище, ім'я")),
                ('surname', models.CharField(blank=True, help_text='Прізвище окремо (опціонально)', max_length=100, verbose_name='Прізвище')),
                ('position', models.CharField(help_text='Посада працівника', max_length=255, verbose_name='Посада')),
                ('group', models.CharField(choices=[('management', 'Управління'), ('zbsi', 'ЗБСІ'), ('iarm', 'ІАРМ'), ('sd_ktk', 'СД КТК'), ('workshop', 'Майстерня'), ('pdtr', 'ПДТР'), ('sl', 'Служба ТЗІ')], default='management', help_text='Підрозділ, до якого належить працівник', max_length=20, verbose_name='Підрозділ')),
                ('is_active', models.BooleanField(default=True, help_text='Чи активний працівник', verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Виконавець',
                'verbose_name_plural': 'Виконавці',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['group', 'is_active'], name='taskFlow_pe_group_19800d_idx'), models.Index(fields=['full_name'], name='taskFlow_pe_full_na_2b1eba_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Унікальна назва проєкту', max_length=255, unique=True, verbose_name='Назва проєкту')),
                ('key', models.CharField(help_text='Короткий код проєкту (наприклад, PROJ, TASK)', max_length=10, unique=True, verbose_name='Ключ проєкту')),
                ('description', models.TextField(blank=True, help_text='Детальний опис проєкту', null=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, help_text='Чи активний проєкт', verbose_name='Активний')),
                ('group', models.CharField(choices=[('management', 'Управління'), ('zbsi', 'ЗБСІ'), ('iarm', 'ІАРМ'), ('sd_ktk', 'СД КТК'), ('workshop', 'Майстерня'), ('pdtr', 'ПДТР'), ('sl', 'Служба ТЗІ')], default='management', help_text='Основний підрозділ проєкту', max_length=20, verbose_name='Підрозділ')),
                ('use_custom_statuses', models.BooleanField(default=False, help_text='Використовувати власні статуси для цього проєкту', verbose_name='Власні статуси')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Проєкт',
                'verbose_name_plural': 'Проєкти',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='taskFlow_pr_is_acti_60e46a_idx'), models.Index(fields=['key'], name='taskFlow_pr_key_424a61_idx')],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва статусу завдання', max_length=50, verbose_name='Назва статусу')),
                ('color', models.CharField(default='bg-gray-500', help_text='Клас кольору Tailwind CSS (наприклад, bg-blue-500)', max_length=20, verbose_name='Колір')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок відображення статусу', verbose_name='Порядок')),
                ('is_default', models.BooleanField(default=False, help_text='Чи є цей статус стандартним для нових завдань', verbose_name='Стандартний')),
                ('is_final', models.BooleanField(default=False, help_text='Чи означає цей статус завершення завдання', verbose_name='Фінальний статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('project', models.ForeignKey(blank=True, help_text='Проєкт (якщо порожньо - глобальний статус)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_statuses', to='taskFlow.project', verbose_name='Проєкт')),
            ],
            options={
                'verbose_name': 'Статус завдання',
                'verbose_name_plural': 'Статуси завдань',
                'ordering': ['project', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, help_text='Автоматично генерується (наприклад, PROJ-123)', max_length=20, unique=True, verbose_name='Ключ завдання')),
                ('title', models.CharField(help_text='Коротка назва завдання', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, help_text='Детальний опис завдання', null=True, verbose_name='Опис')),
                ('department', models.CharField(blank=True, choices=[('management', 'Управління'), ('zbsi', 'ЗБСІ'), ('iarm', 'ІАРМ'), ('sd_ktk', 'СД КТК'), ('workshop', 'Майстерня'), ('pdtr', 'ПДТР'), ('sl', 'Служба ТЗІ')], help_text='Підрозділ, відповідальний за завдання', max_length=20, null=True, verbose_name='Підрозділ')),
                ('due_date', models.DateField(blank=True, help_text='Дедлайн для виконання завдання', null=True, verbose_name='Термін виконання')),
                ('priority', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('critical', 'Критичний')], default='medium', help_text='Пріоритет виконання завдання', max_length=20, verbose_name='Пріоритет')),
                ('is_completed', models.BooleanField(default=False, help_text='Чи виконано завдання', verbose_name='Виконано')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Коли завдання було виконано', null=True, verbose_name='Дата виконання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('assignee', models.ForeignKey(blank=True, help_text='Особа, відповідальна за виконання', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='taskFlow.person', verbose_name='Виконавець')),
                ('created_by', models.ForeignKey(blank=True, help_text='Хто створив завдання', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='taskFlow.person', verbose_name='Автор')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taskFlow.project', verbose_name='Проєкт')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='taskFlow.status', verbose_name='Поточний статус')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Коментар або примітка', verbose_name='Текст коментаря')),
                ('is_system', models.BooleanField(default=False, help_text='Чи є це системний коментар (автоматична зміна)', verbose_name='Системний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='taskFlow.person', verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='taskFlow.task', verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Назва зміненого поля', max_length=50, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Старе значення')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Нове значення')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата зміни')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskFlow.person', verbose_name='Хто змінив')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='taskFlow.task', verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Історія змін',
                'verbose_name_plural': 'Історія змін',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['project', 'order'], name='taskFlow_st_project_44b489_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('name', 'project')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='taskFlow_ta_project_601806_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'is_completed'], name='taskFlow_ta_assigne_b06387_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='taskFlow_ta_due_dat_1cb953_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created_at'], name='taskFlow_ta_created_b19b79_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='taskFlow_ta_task_id_2d4baf_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['task', '-changed_at'], name='taskFlow_ta_task_id_922339_idx'),
        ),
    ]
