# Generated by Django 5.2.1 on 2025-11-18 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0041_project_status_task_and_more'),
        ('taskFlow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oids.person', verbose_name='Хто змінив'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='Особа, відповідальна за виконання', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskflow_assigned_tasks', to='oids.person', verbose_name='Виконавець'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Хто створив завдання', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskflow_created_tasks', to='oids.person', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='oids.person', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.CharField(choices=[('Загальна', 'Загальна'), ('Управління', 'Управління'), ('ЗБСІ', 'ЗБСІ'), ('ІАРМ', 'ІАРМ'), ('СД КТК', 'СД КТК'), ('Майстерня', 'Майстерня'), ('ПДТР', 'ПДТР'), ('СлужбаТЗІ', 'Служба ТЗІ')], default='Загальна', help_text='Основний підрозділ проєкту', max_length=20, verbose_name='Підрозділ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(blank=True, choices=[('Загальна', 'Загальна'), ('Управління', 'Управління'), ('ЗБСІ', 'ЗБСІ'), ('ІАРМ', 'ІАРМ'), ('СД КТК', 'СД КТК'), ('Майстерня', 'Майстерня'), ('ПДТР', 'ПДТР'), ('СлужбаТЗІ', 'Служба ТЗІ')], help_text='Підрозділ, відповідальний за завдання', max_length=20, null=True, verbose_name='Підрозділ'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
