# Generated by Django 5.2.7 on 2025-11-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskFlow', '0002_alter_taskhistory_changed_by_alter_task_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.CharField(choices=[('Загальна', 'Загальна'), ('Управління', 'Управління'), ('ЗБСІ', 'ЗБСІ'), ('ІАРМ', 'ІАРМ'), ('СД КТК', 'СД КТК'), ('Майстерня', 'Майстерня'), ('ПДТР', 'ПДТР'), ('Аудит З ТЗІ', 'Аудит З ТЗІ'), ('СлужбаТЗІ', 'Служба ТЗІ')], default='Загальна', help_text='Основний підрозділ проєкту', max_length=20, verbose_name='Підрозділ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(blank=True, choices=[('Загальна', 'Загальна'), ('Управління', 'Управління'), ('ЗБСІ', 'ЗБСІ'), ('ІАРМ', 'ІАРМ'), ('СД КТК', 'СД КТК'), ('Майстерня', 'Майстерня'), ('ПДТР', 'ПДТР'), ('Аудит З ТЗІ', 'Аудит З ТЗІ'), ('СлужбаТЗІ', 'Служба ТЗІ')], help_text='Підрозділ, відповідальний за завдання', max_length=20, null=True, verbose_name='Підрозділ'),
        ),
    ]
