# Generated by Django 5.2.1 on 2025-05-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255, verbose_name='Приміщення №')),
                ('note', models.TextField(verbose_name='Примітка')),
                ('oid_type', models.CharField(choices=[('ПЕМІН', 'ПЕМІН'), ('МОВНА', 'МОВНА')], default='ПЕМІН', max_length=20)),
                ('status', models.CharField(choices=[('створюється', 'створюється'), ('атестована', 'атестована'), ('в експлуатації', 'в експлуатації'), ('обробка припинена', 'обробка припинена'), ('скасовано', 'скасовано')], default='створюється', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Програма і методика', 'Програма і методика'), ('План пошуку ЗП', 'План пошуку ЗП'), ('Акт пошуку ЗП', 'Акт пошуку ЗП'), ('Протокол1 ІК', 'Протокол1 ІК'), ('Протокол2 ІК', 'Протокол2 ІК'), ('Висновок', 'Висновок'), ('Припис', 'Припис'), ('Акт атестації', 'Акт атестації'), ('Протокол ІК', 'Протокол ІК'), ('Висновок ІК', 'Висновок ІК')], max_length=50)),
                ('document_number', models.CharField(default='27/14-', help_text='Наприклад, 27/14-...', max_length=50)),
                ('process_date', models.DateField(verbose_name='Дата опрацювання')),
                ('work_date', models.DateField(verbose_name='Дата проведення робіт')),
                ('author', models.CharField(max_length=255, verbose_name='Виконав (ПІБ)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.oid')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('management_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.managementunit')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата завершення')),
                ('purpose', models.TextField()),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.oid', verbose_name="Об'єкт")),
                ('persons', models.ManyToManyField(to='oids.person')),
                ('units', models.ManyToManyField(to='oids.unit', verbose_name='Військові частини')),
            ],
        ),
        migrations.AddField(
            model_name='oid',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.unit'),
        ),
    ]
