# Generated by Django 5.2.1 on 2025-05-26 20:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Реєстраційний номер листа до ДССЗЗІ')),
                ('process_date', models.DateField(verbose_name='Дата відправки на реєстрацію в ДССЗЗІ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attestation_docs/', verbose_name='Файл (опційно)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
            ],
            options={
                'verbose_name': 'Реєстрація актів атестації',
                'verbose_name_plural': 'Реєстрації актів атестації',
            },
        ),
        migrations.CreateModel(
            name='OID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_type', models.CharField(choices=[('ПЕМІН', 'ПЕМІН'), ('МОВНА', 'МОВНА')], max_length=10, verbose_name='Тип ОІД')),
                ('cipher', models.CharField(max_length=100, unique=True, verbose_name='Шифр ОІД')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Повна назва ОІД')),
                ('room', models.CharField(max_length=255, verbose_name='Приміщення №')),
                ('status', models.CharField(choices=[('створюється', 'Створюється'), ('отримано ТЗ', 'Отримано ТЗ'), ('отримано заявку', 'Отримано Заявку'), ('активний', 'Активний (наступне проведення робіт)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], default='створюється', max_length=30, verbose_name='Поточний стан ОІД')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
            ],
            options={
                'verbose_name': 'Об’єкт інформаційної діяльності (ОІД)',
                'verbose_name_plural': 'Об’єкти інформаційної діяльності (ОІД)',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="Прізвище, ім'я")),
                ('position', models.CharField(max_length=255, verbose_name='Посада')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Виконавець',
                'verbose_name_plural': 'Виконавці',
            },
        ),
        migrations.CreateModel(
            name='TerritorialManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код управління')),
                ('name', models.CharField(max_length=255, verbose_name='Назва управління')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
            ],
            options={
                'verbose_name': 'Територіальне управління',
                'verbose_name_plural': 'Територіальні управління',
            },
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва групи частин')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
            ],
            options={
                'verbose_name': 'Група військових частин (для відряджень)',
                'verbose_name_plural': 'Групи військових частин (для відряджень)',
            },
        ),
        migrations.CreateModel(
            name='AttestationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_number', models.CharField(max_length=50, verbose_name='Зареєстровано за номером')),
                ('registered_date', models.DateField(verbose_name='Дата реєстрації')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('recorded_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='oids.attestationregistration', verbose_name="Пов'язана реєстрація")),
            ],
            options={
                'verbose_name': 'Відповідь на реєстрацію атестації',
                'verbose_name_plural': 'Відповіді на реєстрацію атестації',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_type', models.CharField(choices=[('МОВНА', 'МОВНА'), ('ПЕМІН', 'ПЕМІН')], max_length=20, verbose_name='Тип ОІД')),
                ('work_type', models.CharField(choices=[('Атестація', 'Атестація'), ('ІК', 'ІК')], max_length=20, verbose_name='Тип робіт')),
                ('name', models.CharField(max_length=100, verbose_name='Назва документа')),
                ('has_expiration', models.BooleanField(default=False, verbose_name='Має термін дії')),
                ('duration_months', models.PositiveIntegerField(default=0, help_text='Якщо документ має термін дії, вкажіть тривалість у місяцях. Якщо не обмежений — залишити 0.', verbose_name='Тривалість (у місяцях)')),
                ('is_required', models.BooleanField(default=True, verbose_name="Обов'язковість")),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типи документів',
                'unique_together': {('oid_type', 'work_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(default='27/14-', max_length=50, verbose_name='Підготовлений № документа')),
                ('process_date', models.DateField(verbose_name='Дата опрацювання')),
                ('work_date', models.DateField(verbose_name='Дата проведення робіт')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attestation_docs/', verbose_name='Прикріплений файл (Опційно)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Дата завершення дії')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oids.documenttype', verbose_name='Тип документа')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='oids.oid', verbose_name='ОІД')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_documents', to='oids.person', verbose_name='Автор документа')),
            ],
            options={
                'verbose_name': 'Опрацьований документ',
                'verbose_name_plural': 'Опрацьовані документи',
            },
        ),
        migrations.CreateModel(
            name='OIDStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30, verbose_name='Попередній статус')),
                ('new_status', models.CharField(max_length=30, verbose_name='Новий статус')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина зміни')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата зміни')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('initiating_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oid_status_changes', to='oids.document', verbose_name='Документ, що ініціював зміну статусу')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='oids.oid', verbose_name='ОІД')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oid_status_changes', to='oids.person', verbose_name='Хто змінив')),
            ],
            options={
                'verbose_name': 'Зміна статусу ОІД',
                'verbose_name_plural': 'Зміни статусу ОІД',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_number', models.CharField(max_length=50, verbose_name='Вхідний номер')),
                ('input_date', models.DateField(verbose_name='Вхідна дата')),
                ('review_result', models.CharField(choices=[('погоджено', 'Погоджено'), ('на доопрацювання', 'На доопрацювання'), ('очікує в папері', 'Очікує в папері')], default='погоджено', max_length=30, verbose_name='Результат розгляду')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_tasks', to='oids.oid', verbose_name='ОІД')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_technical_tasks', to='oids.person', verbose_name='Хто ознайомився')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата початку відрядження')),
                ('end_date', models.DateField(verbose_name='Дата завершення відрядження')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Мета відрядження')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('oids', models.ManyToManyField(related_name='trips', to='oids.oid', verbose_name='Об’єкти інформаційної діяльності, задіяні у відрядженні')),
                ('persons', models.ManyToManyField(related_name='trips', to='oids.person', verbose_name='Особи у відрядженні')),
            ],
            options={
                'verbose_name': 'Відрядження',
                'verbose_name_plural': 'Відрядження',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код частини (номер)')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва військової частини')),
                ('city', models.CharField(max_length=100, verbose_name='Місто розташування')),
                ('distance_from_gu', models.PositiveIntegerField(blank=True, null=True, verbose_name='Відстань від ГУ (км)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('territorial_management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='oids.territorialmanagement', verbose_name='Територіальне управління')),
                ('unit_groups', models.ManyToManyField(blank=True, related_name='units', to='oids.unitgroup', verbose_name='Групи військових частин')),
            ],
            options={
                'verbose_name': 'Військова частина',
                'verbose_name_plural': 'Військові частини',
            },
        ),
        migrations.CreateModel(
            name='TripResultForUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateField(verbose_name='Дата відправки до частини')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='trip_results_docs/', verbose_name='Файл (опційно)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('documents', models.ManyToManyField(related_name='sent_in_trip_results', to='oids.document', verbose_name='Документи до відправки')),
                ('oids', models.ManyToManyField(related_name='received_trip_results', to='oids.oid', verbose_name='ОІД призначення')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_results_for_units', to='oids.trip', verbose_name='Пов’язане відрядження')),
                ('units', models.ManyToManyField(related_name='received_trip_results', to='oids.unit', verbose_name='Військові частини призначення')),
            ],
            options={
                'verbose_name': 'Результати відрядження для частини',
                'verbose_name_plural': 'Результати відрядження для частин',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='units',
            field=models.ManyToManyField(related_name='trips', to='oids.unit', verbose_name='Військові частини призначення'),
        ),
        migrations.AddField(
            model_name='oid',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oids', to='oids.unit', verbose_name='Військова частина'),
        ),
        migrations.AddField(
            model_name='attestationregistration',
            name='units',
            field=models.ManyToManyField(related_name='attestation_registrations', to='oids.unit', verbose_name='Військові частини, що стосуються реєстрації'),
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_number', models.CharField(max_length=50, verbose_name='Вхідний обліковий номер заявки')),
                ('incoming_date', models.DateField(default=django.utils.timezone.now, verbose_name='Вхідна дата заявки')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('status', models.CharField(choices=[('очікує', 'Очікує'), ('в роботі', 'В роботі'), ('виконано', 'Виконано'), ('скасовано', 'Скасовано')], default='очікує', max_length=30, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to='oids.unit', verbose_name='Військова частина')),
            ],
            options={
                'verbose_name': 'Заявка на проведення робіт',
                'verbose_name_plural': 'Заявки на проведення робіт',
                'unique_together': {('unit', 'incoming_number')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='work_requests',
            field=models.ManyToManyField(related_name='trips', to='oids.workrequest', verbose_name="Пов'язані заявки на проведення робіт"),
        ),
        migrations.CreateModel(
            name='WorkRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('Атестація', 'Атестація'), ('ІК', 'ІК')], max_length=20, verbose_name='Запитуваний тип роботи')),
                ('status', models.CharField(choices=[('очікує', 'Очікує'), ('в роботі', 'В роботі'), ('виконано', 'Виконано'), ('скасовано', 'Скасовано')], default='очікує', max_length=30, verbose_name='Статус опрацювання ОІД в заявці')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_request_items', to='oids.oid', verbose_name='Об’єкт інформаційної діяльності')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='oids.workrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Елемент заявки',
                'verbose_name_plural': 'Елементи заявки',
                'unique_together': {('request', 'oid', 'work_type')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='work_request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_documents', to='oids.workrequestitem', verbose_name='Елемент заявки'),
        ),
        migrations.CreateModel(
            name='AttestationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestation_items', to='oids.attestationregistration')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestation_item', to='oids.document', verbose_name='Акт атестації')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestation_registrations', to='oids.oid', verbose_name='ОІД')),
            ],
            options={
                'verbose_name': 'Акт атестації в реєстрації',
                'verbose_name_plural': 'Акти атестації в реєстраціях',
                'unique_together': {('registration', 'oid', 'document')},
            },
        ),
    ]
