# Generated by Django 5.2.1 on 2025-05-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oid',
            name='sec_level',
            field=models.CharField(choices=[('Т', 'Т'), ('Цілком Т', 'Цілком Т'), ('ДСК', 'ДСК')], default='Т', max_length=10, verbose_name='Гриф ОІД'),
        ),
    ]
