# Generated by Django 5.2.1 on 2025-05-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='management_unit',
            field=models.CharField(choices=[('ПівнічнеТУ', 'ПівнічнеТУ'), ('ПівденнеТУ', 'ПівденнеТУ'), ('ЗахіднеТУ', 'ЗахіднеТУ'), ('СхіднеТУ', 'СхіднеТУ'), ('ЦентральнеТУ', 'ЦентральнеТУ')], max_length=50, verbose_name='Управління'),
        ),
        migrations.DeleteModel(
            name='ManagementUnit',
        ),
    ]
