# Generated by Django 5.2.1 on 2025-06-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestationregistration',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='oid_type',
            field=models.CharField(choices=[('МОВНА', 'МОВНА'), ('ПЕМІН', 'ПЕМІН'), ('СПІЛЬНИЙ', 'СПІЛЬНИЙ')], max_length=20, verbose_name='Тип ОІД'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='work_type',
            field=models.CharField(choices=[('Атестація', 'Атестація'), ('ІК', 'ІК'), ('СПІЛЬНИЙ', 'СПІЛЬНИЙ')], max_length=20, verbose_name='Тип робіт'),
        ),
    ]
