# Generated by Django 5.2.1 on 2025-05-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oid',
            name='sec_level',
            field=models.CharField(choices=[('Таємно', 'Таємно'), ('Цілком таємно', 'Цілком таємно'), ('ДСК', 'Для службового користування')], default=1, max_length=15, verbose_name='Гриф'),
            preserve_default=False,
        ),
    ]
