# Generated by Django 5.2.1 on 2025-05-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Part',
            new_name='MBase',
        ),
        migrations.RenameField(
            model_name='oid',
            old_name='part',
            new_name='MBase',
        ),
        migrations.AddField(
            model_name='oid',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('program', 'Програма'), ('plan', 'План'), ('act', 'Акт'), ('other', 'Інше')], max_length=20)),
                ('doc_number', models.CharField(max_length=100)),
                ('doc_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.oid')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='oids.workhistory')),
            ],
        ),
    ]
