# Generated by Django 5.2.1 on 2025-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attestation_docs/', verbose_name='Прикріплений файл (Опційно)'),
        ),
    ]
