# Generated by Django 5.2.1 on 2025-05-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Unit',
            new_name='unit',
        ),
    ]
