# Generated by Django 5.2.1 on 2025-05-21 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicaltask',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата додання інформації'),
            preserve_default=False,
        ),
    ]
