# Generated by Django 5.2.1 on 2025-05-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0002_alter_unit_management_unit_delete_managementunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='directionGroup',
            field=models.CharField(default=1, max_length=10, verbose_name='грапа частин в які часто їдимо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='distance',
            field=models.CharField(default=2, max_length=10, verbose_name='відстань КМ'),
            preserve_default=False,
        ),
    ]
