# Generated by Django 5.2.1 on 2025-05-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0002_alter_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workrequest',
            old_name='Unit',
            new_name='unit',
        ),
        migrations.CreateModel(
            name='WorkRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('Атестація', 'Атестація'), ('ІК', 'ІК')], max_length=20)),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.oid')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='oids.workrequest')),
            ],
        ),
    ]
