# Generated by Django 5.2.1 on 2025-05-27 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0002_oid_sec_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicaltask',
            name='read_till_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Опрацювати до'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technicaltask',
            name='review_result',
            field=models.CharField(choices=[('працювати', 'Опрацювати'), ('очікує в папері', 'Очікує в папері'), ('погоджено', 'Погоджено'), ('на доопрацювання', 'На доопрацювання')], default='погоджено', max_length=30, verbose_name='Результат розгляду'),
        ),
    ]
