# Generated by Django 5.2.1 on 2025-05-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0002_technicaltask_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('атестована', 'Атестована'), ('в експлуатації', 'В експлуатації'), ('обробка призупинена', 'Обробка призупинена'), ('скасовано', 'Скасовано')], default='створюється', max_length=30, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='status',
            field=models.CharField(choices=[('нова заявка', 'Нова заявка'), ('Заявка в роботі', 'Заявка в роботі'), ('Заявка виконана', 'Заявка виконана'), ('Заявка скасована', 'Заявка скасована')], default='нова заявка', max_length=30, verbose_name='Поточний стан заявки'),
        ),
    ]
