# Generated by Django 5.2.1 on 2025-05-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0002_rename_part_mbase_rename_part_oid_mbase_oid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oid',
            name='OID_type',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AlterField(
            model_name='oid',
            name='status',
            field=models.CharField(choices=[('створюється', 'створюється'), ('атестована', 'атестована'), ('в експлуатації', 'в експлуатації'), ('обробка припинена', 'обробка припинена'), ('скасовано', 'скасовано')], max_length=100),
        ),
    ]
