# Generated by Django 5.2.1 on 2025-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0002_document_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='oid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення запису'),
        ),
    ]
