# Generated by Django 5.2.1 on 2025-06-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0002_remove_attestationregistration_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestationresponse',
            name='attachment',
        ),
    ]
