# Generated by Django 5.2.1 on 2025-05-19 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0003_rename_unit_workrequest_unit_workrequestitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, verbose_name='Номер Акту Атестації')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.oid', verbose_name='ОІД')),
            ],
        ),
        migrations.CreateModel(
            name='AttestationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateField(verbose_name='Дата відправки на реєстрацію')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attestation_docs/', verbose_name='Файл (опційно)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('oids', models.ManyToManyField(through='oids.AttestationItem', to='oids.oid', verbose_name='ОІД для реєстрації')),
                ('units', models.ManyToManyField(to='oids.unit', verbose_name='Військові частини')),
            ],
        ),
        migrations.AddField(
            model_name='attestationitem',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.attestationregistration'),
        ),
    ]
