# Generated by Django 5.2.1 on 2025-05-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0003_alter_oid_status_alter_workrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='work_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oids.workrequest', verbose_name='Заявка на проведення робіт'),
        ),
    ]
