# Generated by Django 5.2.1 on 2025-05-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0003_oid_oid_type_alter_oid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oid',
            name='OID_type',
            field=models.CharField(choices=[('МОВНА', 'МОВНА'), ('ПЕОМ', 'ПЕОМ')], max_length=10),
        ),
    ]
