# Generated by Django 5.2.1 on 2025-06-01 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0003_remove_attestationresponse_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripresultforunit',
            name='attachment',
        ),
        migrations.AddField(
            model_name='tripresultforunit',
            name='outgoing_letter_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Вих. дата супровідного листа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripresultforunit',
            name='outgoing_letter_number',
            field=models.CharField(default=2, max_length=50, verbose_name='Вих. номер супровідного листа'),
            preserve_default=False,
        ),
    ]
