# Generated by Django 5.2.1 on 2025-06-01 07:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0003_technicaltask_read_till_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attestationregistration',
            options={'ordering': ['-outgoing_letter_date', '-id'], 'verbose_name': 'Відправка актів на реєстрацію (ДССЗЗІ)', 'verbose_name_plural': 'Відправки актів на реєстрацію (ДССЗЗІ)'},
        ),
        migrations.AlterModelOptions(
            name='attestationresponse',
            options={'ordering': ['-response_letter_date', '-id'], 'verbose_name': 'Відповідь на реєстрацію (ДССЗЗІ)', 'verbose_name_plural': 'Відповіді на реєстрацію (ДССЗЗІ)'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-process_date', '-work_date'], 'verbose_name': 'Опрацьований документ', 'verbose_name_plural': 'Опрацьовані документи'},
        ),
        migrations.RemoveField(
            model_name='attestationregistration',
            name='process_date',
        ),
        migrations.RemoveField(
            model_name='attestationregistration',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='attestationresponse',
            name='recorded_date',
        ),
        migrations.RemoveField(
            model_name='attestationresponse',
            name='registered_date',
        ),
        migrations.RemoveField(
            model_name='attestationresponse',
            name='registered_number',
        ),
        migrations.RemoveField(
            model_name='attestationresponse',
            name='registration',
        ),
        migrations.AddField(
            model_name='attestationregistration',
            name='outgoing_letter_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата вихідного листа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attestationregistration',
            name='outgoing_letter_number',
            field=models.CharField(default=1, max_length=50, verbose_name='Вихідний номер листа до ДССЗЗІ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attestationregistration',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_attestation_packages', to='oids.person', verbose_name='Хто відправив лист'),
        ),
        migrations.AddField(
            model_name='attestationregistration',
            name='status',
            field=models.CharField(choices=[('sent', 'Відправлено, очікує відповіді'), ('received', 'Відповідь отримано'), ('canceled', 'Скасовано (відправку)')], default='sent', max_length=25, verbose_name='Статус відправки'),
        ),
        migrations.AddField(
            model_name='attestationresponse',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attestation_responses_received/', verbose_name='Скан-копія листа-відповіді (опційно)'),
        ),
        migrations.AddField(
            model_name='attestationresponse',
            name='attestation_registration_sent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='response_received', to='oids.attestationregistration', verbose_name="Пов'язана відправка (вихідний лист)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attestationresponse',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_attestation_responses', to='oids.person', verbose_name='Хто отримав/вніс відповідь'),
        ),
        migrations.AddField(
            model_name='attestationresponse',
            name='response_letter_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата вхідного листа-відповіді'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attestationresponse',
            name='response_letter_number',
            field=models.CharField(default=1, max_length=50, verbose_name='Вхідний номер листа-відповіді'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='attestation_registration_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_documents', to='oids.attestationregistration', verbose_name='Відправлено на реєстрацію ДССЗЗІ (в складі листа)'),
        ),
        migrations.AddField(
            model_name='document',
            name='dsszzi_registered_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата реєстрації в ДССЗЗІ (для цього акту)'),
        ),
        migrations.AddField(
            model_name='document',
            name='dsszzi_registered_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Зареєстрований номер в ДССЗЗІ (для цього акту)'),
        ),
        migrations.AlterField(
            model_name='attestationregistration',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attestation_registrations_sent/', verbose_name='Скан-копія вихідного листа (опційно)'),
        ),
        migrations.AlterField(
            model_name='attestationregistration',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітка до відправки'),
        ),
        migrations.AlterField(
            model_name='attestationregistration',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='sent_for_attestation_registrations', to='oids.unit', verbose_name='Військові частини (акти яких включено)'),
        ),
        migrations.AlterField(
            model_name='attestationresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attestationresponse',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітка до відповіді'),
        ),
        migrations.AlterField(
            model_name='attestationresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='AttestationItem',
        ),
    ]
