# Generated by Django 5.2.1 on 2025-05-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0003_unit_directiongroup_unit_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(default='27/14-', help_text='Наприклад, 27/14-...', max_length=50, verbose_name='Підготовлений № документу'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Програма і методика', 'Програма і методика'), ('План пошуку ЗП', 'План пошуку ЗП'), ('Акт пошуку ЗП', 'Акт пошуку ЗП'), ('Протокол1 ІК', 'Протокол1 ІК'), ('Протокол2 ІК', 'Протокол2 ІК'), ('Висновок', 'Висновок'), ('Припис', 'Припис'), ('Акт атестації', 'Акт атестації'), ('Протокол ІК', 'Протокол ІК'), ('Висновок ІК', 'Висновок ІК')], max_length=50, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.oid', verbose_name='ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.unit', verbose_name='Військова частина'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='oid_type',
            field=models.CharField(choices=[('ПЕМІН', 'ПЕМІН'), ('МОВНА', 'МОВНА')], default='ПЕМІН', max_length=20, verbose_name='Тип ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='status',
            field=models.CharField(choices=[('створюється', 'створюється'), ('атестована', 'атестована'), ('в експлуатації', 'в експлуатації'), ('обробка припинена', 'обробка припинена'), ('скасовано', 'скасовано')], default='створюється', max_length=30, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='П.І.Б.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='persons',
            field=models.ManyToManyField(to='oids.person', verbose_name='Відряджаються'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='city',
            field=models.CharField(max_length=25, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Військова частина'),
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('Атестація', 'Атестація'), ('ІК', 'ІК')], max_length=20, verbose_name='Тип роботи')),
                ('incoming_number', models.CharField(max_length=50, verbose_name='Вхідний номер заявки')),
                ('incoming_date', models.DateField(verbose_name='Дата заявки')),
                ('status', models.CharField(choices=[('очікує', 'очікує'), ('в роботі', 'в роботі'), ('виконано', 'виконано'), ('скасовано', 'скасовано')], default='очікує', max_length=20, verbose_name='Статус заявки')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.unit', verbose_name='Військова частина')),
                ('oids', models.ManyToManyField(to='oids.oid', verbose_name='Об’єкти інформаційної діяльності')),
            ],
        ),
    ]
