# Generated by Django 5.2.1 on 2025-06-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0004_remove_tripresultforunit_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['oid_type', 'work_type', 'name'], 'verbose_name': 'Тип документа', 'verbose_name_plural': 'Типи документів'},
        ),
        migrations.AlterModelOptions(
            name='workrequestitem',
            options={'ordering': ['request', 'oid'], 'verbose_name': 'Елемент заявки', 'verbose_name_plural': 'Елементи заявки'},
        ),
    ]
