# Generated by Django 5.2.1 on 2025-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0004_attestationitem_attestationregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripResultForUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateField(verbose_name='Дата відправки до частини')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='trip_results_docs/', verbose_name='Файл (опційно)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('documents', models.ManyToManyField(to='oids.document', verbose_name='Документи до відправки')),
                ('oids', models.ManyToManyField(to='oids.oid', verbose_name='ОІД призначення')),
                ('units', models.ManyToManyField(to='oids.unit', verbose_name='Військові частини призначення')),
            ],
        ),
    ]
