# Generated by Django 5.2.1 on 2025-05-16 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0004_alter_oid_oid_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date, null=True),
        ),
    ]
