# Generated by Django 5.2.1 on 2025-05-16 19:10

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0004_alter_document_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oid',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='work_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Атестація', 'Атестація'), ('ІК', 'ІК')], max_length=12, verbose_name='Типи роботи'),
        ),
    ]
