# Generated by Django 5.2.1 on 2025-05-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0004_document_work_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='oid',
        ),
        migrations.AddField(
            model_name='trip',
            name='oids',
            field=models.ManyToManyField(to='oids.oid', verbose_name='Об’єкти інформаційної діяльності'),
        ),
        migrations.AddField(
            model_name='trip',
            name='work_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oids.workrequest', verbose_name='Заявка на проведення робіт'),
            preserve_default=False,
        ),
    ]
