# Generated by Django 5.2.1 on 2025-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0005_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateTimeField(blank=True, default=(2016, 3, 1), null=True),
        ),
    ]
