# Generated by Django 5.2.1 on 2025-05-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0005_tripresultforunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_number', models.CharField(max_length=50, verbose_name='Вхідний номер')),
                ('input_date', models.DateField(verbose_name='Вхідна дата')),
                ('reviewed_by', models.CharField(max_length=255, verbose_name='Хто ознайомився')),
                ('review_result', models.CharField(choices=[('погоджено', 'Погоджено'), ('на доопрацювання', 'На доопрацювання'), ('чекаємо папір', 'Чекаємо папір')], max_length=30, verbose_name='Результат розгляду')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='oids.oid', verbose_name='ОІД')),
            ],
        ),
    ]
