# Generated by Django 5.2.1 on 2025-05-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0005_remove_trip_oid_trip_oids_trip_work_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='work_request',
        ),
        migrations.AddField(
            model_name='trip',
            name='work_requests',
            field=models.ManyToManyField(to='oids.workrequest', verbose_name='Заявки на проведення робіт'),
        ),
    ]
