# Generated by Django 5.2.1 on 2025-05-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0005_alter_oid_note_alter_workrequest_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='oid',
        ),
        migrations.AlterField(
            model_name='trip',
            name='purpose',
            field=models.TextField(blank=True, null=True, verbose_name='Примітка'),
        ),
        migrations.AddField(
            model_name='trip',
            name='oid',
            field=models.ManyToManyField(to='oids.oid', verbose_name='Які ОІД'),
        ),
    ]
