# Generated by Django 5.2.1 on 2025-06-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0005_alter_documenttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('отримано ТЗ', 'Отримано ТЗ'), ('отримано заявку', 'Отримано Заявку'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], default='створюється', max_length=30, verbose_name='Поточний стан ОІД'),
        ),
    ]
