# Generated by Django 5.2.1 on 2025-05-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0006_alter_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
