# Generated by Django 5.2.1 on 2025-05-16 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0006_remove_trip_oid_alter_trip_purpose_trip_oid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва документа')),
                ('oid_type', models.CharField(choices=[('МОВНА', 'МОВНА'), ('ПЕОМ', 'ПЕОМ')], max_length=20, verbose_name='Тип ОІД')),
                ('work_type', models.CharField(choices=[('Атестація', 'Атестація'), ('ІК', 'ІК')], max_length=20, verbose_name='Тип робіт')),
                ('valid_days', models.PositiveIntegerField(default=0, help_text='Наприклад, 20 або 60. Якщо не обмежений — залишити 0.', verbose_name='Строк дії (у місяцях)')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Виконавець (ПІБ)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oids.documenttype', verbose_name='Тип документа'),
        ),
    ]
