# Generated by Django 5.2.1 on 2025-05-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationregistration',
            name='oids',
            field=models.ManyToManyField(through='oids.AttestationItem', to='oids.oid', verbose_name='ОІД що реєструються'),
        ),
        migrations.AlterField(
            model_name='attestationregistration',
            name='process_date',
            field=models.DateField(verbose_name='Дата відправки на реєстрацію в ДССЗЗІ'),
        ),
    ]
