# Generated by Django 5.2.1 on 2025-06-02 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0006_alter_oid_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicaltask',
            options={'ordering': ['-input_date', '-read_till_date', '-created_at'], 'verbose_name': 'Технічне Завдання', 'verbose_name_plural': 'Технічні Завдання'},
        ),
        migrations.AlterField(
            model_name='technicaltask',
            name='review_result',
            field=models.CharField(choices=[('опрацювати', 'Опрацювати'), ('очікує в папері', 'Очікує в папері'), ('погоджено', 'Погоджено'), ('на доопрацювання', 'На доопрацювання')], max_length=30, verbose_name='Результат розгляду / Статус ТЗ'),
        ),
        migrations.AlterField(
            model_name='technicaltask',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_technical_tasks', to='oids.person', verbose_name='Хто ознайомився/опрацював'),
        ),
    ]
