# Generated by Django 5.2.1 on 2025-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0006_remove_trip_work_request_trip_work_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequestitem',
            name='status',
            field=models.CharField(choices=[('нова заявка', 'Нова заявка'), ('Заявка в роботі', 'Заявка в роботі'), ('Заявка виконана', 'Заявка виконана'), ('Заявка скасована', 'Заявка скасована')], default='нова заявка', max_length=30, verbose_name='Статус опрацювання ОІД'),
        ),
    ]
