# Generated by Django 5.2.1 on 2025-05-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0007_alter_attestationregistration_oids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='oid_type',
            field=models.CharField(choices=[('ПЕМІН', 'ПЕМІН'), ('МОВНА', 'МОВНА')], default='ПЕМІН', max_length=20, verbose_name='Тип ОІД'),
        ),
        migrations.AlterField(
            model_name='document',
            name='work_type',
            field=models.CharField(choices=[('Атестація', 'Атестація'), ('ІК', 'ІК')], default='ІК', max_length=20, verbose_name='Тип роботи'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('атестована', 'атестована'), ('в експлуатації', 'В експлуатації'), ('обробка призупинена', 'обробка призупинена'), ('скасовано', 'скасовано')], default='створюється', max_length=30, verbose_name='Поточний стан ОІД'),
        ),
    ]
