# Generated by Django 5.2.1 on 2025-05-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0007_alter_document_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date',
        ),
    ]
