# Generated by Django 5.2.1 on 2025-05-16 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0007_documenttype_alter_document_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='work_type',
            field=models.CharField(choices=[('Атестація', 'Атестація'), ('ІК', 'ІК')], default=4, max_length=20, verbose_name='Тип роботи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.documenttype', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='oid_type',
            field=models.CharField(choices=[('МОВНА', 'МОВНА'), ('ПЕМІН', 'ПЕМІН')], max_length=20, verbose_name='Тип ОІД'),
        ),
    ]
