# Generated by Django 5.2.1 on 2025-06-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0008_historicalattestationregistration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workrequestitem',
            options={'ordering': ['request', 'request__incoming_date'], 'verbose_name': 'Елемент заявки', 'verbose_name_plural': 'Елементи заявки'},
        ),
        migrations.AddField(
            model_name='historicalworkrequestitem',
            name='doc_processing_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Термін опрацювання документів до'),
        ),
        migrations.AddField(
            model_name='historicalworkrequestitem',
            name='docs_actually_processed_on',
            field=models.DateField(blank=True, null=True, verbose_name='Документи фактично опрацьовано (дата)'),
        ),
        migrations.AddField(
            model_name='workrequestitem',
            name='doc_processing_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Термін опрацювання документів до'),
        ),
        migrations.AddField(
            model_name='workrequestitem',
            name='docs_actually_processed_on',
            field=models.DateField(blank=True, null=True, verbose_name='Документи фактично опрацьовано (дата)'),
        ),
    ]
