# Generated by Django 5.2.1 on 2025-05-20 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0008_document_oid_type_alter_document_work_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oid',
            name='oid_type',
            field=models.CharField(choices=[('ПЕМІН', 'ПЕМІН'), ('МОВНА', 'МОВНА')], default='ПЕМІН', max_length=10, verbose_name='Тип ОІД'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('атестована', 'атестована'), ('в експлуатації', 'В експлуатації'), ('обробка призупинена', 'обробка призупинена'), ('скасовано', 'скасовано')], default='створюється', max_length=30, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='work_type',
            field=models.CharField(choices=[('Атестація', 'Атестація'), ('ІК', 'ІК')], default='ІК', max_length=20, verbose_name='Тип роботи'),
        ),
        migrations.AlterField(
            model_name='workrequestitem',
            name='work_type',
            field=models.CharField(choices=[('Атестація', 'Атестація'), ('ІК', 'ІК')], default='ІК', max_length=20, verbose_name='Тип роботи'),
        ),
        migrations.CreateModel(
            name='TechnicalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_number', models.CharField(max_length=50, verbose_name='Вхідний номер')),
                ('input_date', models.DateField(verbose_name='Вхідна дата')),
                ('reviewed_by', models.CharField(max_length=255, verbose_name='Хто ознайомився')),
                ('review_result', models.CharField(choices=[('погоджено', 'Погоджено'), ('на доопрацювання', 'На доопрацювання'), ('чекаємо папір', 'Чекаємо папір')], default='погоджено', max_length=30, verbose_name='Результат розгляду')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TechnicalTasks', to='oids.oid', verbose_name='ОІД')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
