# Generated by Django 5.2.1 on 2025-06-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0009_alter_workrequestitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloid',
            name='cipher',
            field=models.CharField(max_length=100, verbose_name='Шифр ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='cipher',
            field=models.CharField(max_length=100, verbose_name='Шифр ОІД'),
        ),
    ]
