# Generated by Django 5.2.1 on 2025-05-21 03:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0009_alter_oid_oid_type_alter_workrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestationitem',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Реєстраційний номер листа до ДССЗЗІ'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата внесення в систему'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oid',
            name='created_by_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_doc_for_oid', to='oids.document', verbose_name='Перший документ (Атестація/ІК)'),
        ),
        migrations.AddField(
            model_name='oid',
            name='latest_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_doc_for_oid', to='oids.document', verbose_name='Останній документ'),
        ),
        migrations.AddField(
            model_name='tripresultforunit',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oids.workrequest', verbose_name='Пов’язана заявка'),
        ),
        migrations.AddField(
            model_name='tripresultforunit',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oids.trip', verbose_name='Пов’язане відрядження'),
        ),
    ]
