# Generated by Django 5.2.1 on 2025-06-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0010_alter_historicaloid_cipher_alter_oid_cipher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripresultforunit',
            options={'ordering': ['-process_date', '-id'], 'verbose_name': 'Результати відрядження для частини', 'verbose_name_plural': 'Результати відрядження для частин'},
        ),
    ]
