# Generated by Django 5.2.1 on 2025-06-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0011_alter_tripresultforunit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_date', '-id'], 'verbose_name': 'Відрядження', 'verbose_name_plural': 'Відрядження'},
        ),
    ]
