# Generated by Django 5.2.1 on 2025-06-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0012_alter_trip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripresultforunit',
            options={'ordering': ['-outgoing_letter_date', '-id'], 'verbose_name': 'Результати відрядження для частини', 'verbose_name_plural': 'Результати відрядження для частин'},
        ),
        migrations.RemoveField(
            model_name='historicaltripresultforunit',
            name='process_date',
        ),
        migrations.RemoveField(
            model_name='tripresultforunit',
            name='process_date',
        ),
    ]
