# Generated by Django 5.2.1 on 2025-06-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0013_alter_tripresultforunit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkrequestitem',
            name='deadline_trigger_trip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.trip', verbose_name='Відрядження, що встановило дедлайн опрацювання'),
        ),
        migrations.AddField(
            model_name='workrequestitem',
            name='deadline_trigger_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oids.trip', verbose_name='Відрядження, що встановило дедлайн опрацювання'),
        ),
    ]
