# Generated by Django 5.2.1 on 2025-06-16 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0014_historicalworkrequestitem_deadline_trigger_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloid',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Інвентарний номер'),
        ),
        migrations.AddField(
            model_name='historicaloid',
            name='pemin_sub_type',
            field=models.CharField(blank=True, choices=[('ВАРМ', 'ВАРМ'), ('АС1Стаціонар', 'АС1 Стаціонар'), ('АС1Getac', 'АС1 Getac')], max_length=20, null=True, verbose_name='Тип ЕОТ'),
        ),
        migrations.AddField(
            model_name='historicaloid',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серійний номер'),
        ),
        migrations.AddField(
            model_name='oid',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Інвентарний номер'),
        ),
        migrations.AddField(
            model_name='oid',
            name='pemin_sub_type',
            field=models.CharField(blank=True, choices=[('ВАРМ', 'ВАРМ'), ('АС1Стаціонар', 'АС1 Стаціонар'), ('АС1Getac', 'АС1 Getac')], max_length=20, null=True, verbose_name='Тип ЕОТ'),
        ),
        migrations.AddField(
            model_name='oid',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='workrequestitem',
            name='deadline_trigger_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_work_items', to='oids.trip', verbose_name='Відрядження, що встановило дедлайн опрацювання'),
        ),
    ]
