# Generated by Django 5.2.1 on 2025-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0016_alter_historicaloid_pemin_sub_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесення інф. про реєстрацію Атестації'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесення документу'),
        ),
        migrations.AlterField(
            model_name='historicalattestationregistration',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата внесення інф. про реєстрацію Атестації'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата внесення документу'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата створення ОІД'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='sec_level',
            field=models.CharField(choices=[('Таємно', 'Таємно'), ('Цілком таємно', 'Цілком таємно')], max_length=15, verbose_name='Гриф'),
        ),
        migrations.AlterField(
            model_name='historicaltechnicaltask',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата внесення ТЗ\\МЗ'),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата створення відрядження'),
        ),
        migrations.AlterField(
            model_name='historicaltripresultforunit',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата внесення запису про опрацювання відрядження'),
        ),
        migrations.AlterField(
            model_name='historicalworkrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата внесення заявки'),
        ),
        migrations.AlterField(
            model_name='historicalworkrequestitem',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата внесення Item заявки'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='sec_level',
            field=models.CharField(choices=[('Таємно', 'Таємно'), ('Цілком таємно', 'Цілком таємно')], max_length=15, verbose_name='Гриф'),
        ),
        migrations.AlterField(
            model_name='oidstatuschange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису про зміну статусу'),
        ),
        migrations.AlterField(
            model_name='technicaltask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесення ТЗ\\МЗ'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення відрядження'),
        ),
        migrations.AlterField(
            model_name='tripresultforunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесення запису про опрацювання відрядження'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесення заявки'),
        ),
        migrations.AlterField(
            model_name='workrequestitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесення Item заявки'),
        ),
    ]
