# Generated by Django 5.2.1 on 2025-06-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0017_alter_attestationregistration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltechnicaltask',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата останнього? оновлення статусу'),
        ),
        migrations.AlterField(
            model_name='technicaltask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата останнього? оновлення статусу'),
        ),
    ]
