# Generated by Django 5.2.1 on 2025-06-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0018_alter_historicaltechnicaltask_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltechnicaltask',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата опрацювання'),
        ),
        migrations.AlterField(
            model_name='technicaltask',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата опрацювання'),
        ),
    ]
