# Generated by Django 5.2.1 on 2025-06-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0020_alter_historicaltechnicaltask_review_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloid',
            name='pemin_sub_type',
            field=models.CharField(blank=True, choices=[('ВАРМ', 'ВАРМ'), ('АС1Стаціонар', 'АС1 Стаціонар'), ('АС1Портативний', 'АС1 Портативний'), ('МОВНА', 'МОВНА')], max_length=20, null=True, verbose_name='Тип ЕОТ'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='pemin_sub_type',
            field=models.CharField(blank=True, choices=[('ВАРМ', 'ВАРМ'), ('АС1Стаціонар', 'АС1 Стаціонар'), ('АС1Портативний', 'АС1 Портативний'), ('МОВНА', 'МОВНА')], max_length=20, null=True, verbose_name='Тип ЕОТ'),
        ),
    ]
