# Generated by Django 5.2.1 on 2025-06-23 11:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0021_alter_historicaloid_pemin_sub_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDocumentType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('oid_type', models.CharField(choices=[('МОВНА', 'МОВНА'), ('ПЕМІН', 'ПЕМІН'), ('СПІЛЬНИЙ', 'СПІЛЬНИЙ')], max_length=20, verbose_name='Тип ОІД')),
                ('work_type', models.CharField(choices=[('Атестація', 'Атестація'), ('ІК', 'ІК'), ('СПІЛЬНИЙ', 'СПІЛЬНИЙ')], max_length=20, verbose_name='Тип робіт')),
                ('name', models.CharField(max_length=100, verbose_name='Назва документа')),
                ('has_expiration', models.BooleanField(default=False, verbose_name='Має термін дії')),
                ('duration_months', models.PositiveIntegerField(default=0, help_text='Якщо документ має термін дії, вкажіть тривалість у місяцях. Якщо не обмежений — залишити 0.', verbose_name='Тривалість (у місяцях)')),
                ('is_required', models.BooleanField(default=True, verbose_name="Обов'язковість")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Тип документа',
                'verbose_name_plural': 'historical Типи документів',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOIDStatusChange',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30, verbose_name='Попередній статус')),
                ('new_status', models.CharField(max_length=30, verbose_name='Новий статус')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина зміни')),
                ('changed_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата зміни')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата створення запису про зміну статусу')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата останнього оновлення')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.person', verbose_name='Хто змінив')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('initiating_document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.document', verbose_name='Документ, що ініціював зміну статусу')),
                ('oid', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.oid', verbose_name='ОІД')),
            ],
            options={
                'verbose_name': 'historical Зміна статусу ОІД',
                'verbose_name_plural': 'historical Зміни статусу ОІД',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="Прізвище, ім'я")),
                ('position', models.CharField(max_length=255, verbose_name='Посада')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Виконавець',
                'verbose_name_plural': 'historical Виконавці',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUnit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Код частини (номер)')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва військової частини')),
                ('city', models.CharField(max_length=100, verbose_name='Місто розташування')),
                ('distance_from_gu', models.PositiveIntegerField(blank=True, null=True, verbose_name='Відстань від ГУ (км)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('territorial_management', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.territorialmanagement', verbose_name='Територіальне управління')),
            ],
            options={
                'verbose_name': 'historical Військова частина',
                'verbose_name_plural': 'historical Військові частини',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
