# Generated by Django 5.2.1 on 2025-06-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0022_historicaldocumenttype_historicaloidstatuschange_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='historicaldocumenttype',
            name='is_required',
        ),
    ]
