# Generated by Django 5.2.1 on 2025-06-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0023_remove_documenttype_is_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloid',
            name='sec_level',
            field=models.CharField(choices=[('Таємно', 'Таємно'), ('Цілком таємно', 'Цілком таємно'), ('уточнити', 'уточнити')], max_length=15, verbose_name='Гриф'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='sec_level',
            field=models.CharField(choices=[('Таємно', 'Таємно'), ('Цілком таємно', 'Цілком таємно'), ('уточнити', 'уточнити')], max_length=15, verbose_name='Гриф'),
        ),
    ]
