# Generated by Django 5.2.1 on 2025-06-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0024_alter_historicaloid_sec_level_alter_oid_sec_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloid',
            name='pemin_sub_type',
            field=models.CharField(blank=True, choices=[('ВАРМ', 'ВАРМ'), ('АС1Стаціонар(стандарт)', 'АС1 Стаціонар (стандарт)'), ('АС1Портативний(стандарт)', 'АС1 Портативний (стандарт)'), ('АС1Стаціонар(поВійні)', 'АС1 Стаціонар (по війні)'), ('АС1Портативний(поВійні)', 'АС1 Портативний (по війні)'), ('МОВНА', 'МОВНА')], max_length=25, null=True, verbose_name='Тип ЕОТ'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='pemin_sub_type',
            field=models.CharField(blank=True, choices=[('ВАРМ', 'ВАРМ'), ('АС1Стаціонар(стандарт)', 'АС1 Стаціонар (стандарт)'), ('АС1Портативний(стандарт)', 'АС1 Портативний (стандарт)'), ('АС1Стаціонар(поВійні)', 'АС1 Стаціонар (по війні)'), ('АС1Портативний(поВійні)', 'АС1 Портативний (по війні)'), ('МОВНА', 'МОВНА')], max_length=25, null=True, verbose_name='Тип ЕОТ'),
        ),
    ]
