# Generated by Django 5.2.1 on 2025-06-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0025_alter_historicaloid_pemin_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
    ]
