# Generated by Django 5.2.1 on 2025-06-27 17:33

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0026_historicalunit_is_active_unit_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва шаблону процесу')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('applies_to_oid_type', multiselectfield.db.fields.MultiSelectField(choices=[('ПЕМІН', 'ПЕМІН'), ('МОВНА', 'МОВНА')], max_length=100, verbose_name='Тип ОІД')),
                ('applies_to_pemin_subtype', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('МОВНА', 'МОВНА'), ('ВАРМ', 'ВАРМ'), ('ЗАРМ', 'ЗАРМ'), ('АС1_23Портативний', 'АС1-2/3 Портативний'), ('АС1_23Стаціонар', 'АС1-2/3 Стаціонар'), ('АС1_4ДСК', 'АС1-4 ДСК'), ('АС23_4МОСІ', 'АС23-4 МОСІ Соц і т.п.')], max_length=100, null=True, verbose_name='Підтип ПЕМІН')),
                ('is_active', models.BooleanField(default=True, help_text='Чи можна використовувати цей шаблон для нових ОІД', verbose_name='Активний')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('чернетка', 'Чернетка'), ('надіслано на реєстрацію', 'Надіслано на реєстрацію'), ('зареєстровано', 'Зареєстровано'), ('надіслано до в/ч', 'Надіслано до в/ч'), ('завершено', 'Завершено')], db_index=True, default='чернетка', max_length=30, verbose_name='Статус опрацювання документа'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='processing_status',
            field=models.CharField(choices=[('чернетка', 'Чернетка'), ('надіслано на реєстрацію', 'Надіслано на реєстрацію'), ('зареєстровано', 'Зареєстровано'), ('надіслано до в/ч', 'Надіслано до в/ч'), ('завершено', 'Завершено')], db_index=True, default='чернетка', max_length=30, verbose_name='Статус опрацювання документа'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='pemin_sub_type',
            field=models.CharField(blank=True, choices=[('МОВНА', 'МОВНА'), ('ВАРМ', 'ВАРМ'), ('ЗАРМ', 'ЗАРМ'), ('АС1_23Портативний', 'АС1-2/3 Портативний'), ('АС1_23Стаціонар', 'АС1-2/3 Стаціонар'), ('АС1_4ДСК', 'АС1-4 ДСК'), ('АС23_4МОСІ', 'АС23-4 МОСІ Соц і т.п.')], max_length=25, null=True, verbose_name='Тип ЕОТ'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='pemin_sub_type',
            field=models.CharField(blank=True, choices=[('МОВНА', 'МОВНА'), ('ВАРМ', 'ВАРМ'), ('ЗАРМ', 'ЗАРМ'), ('АС1_23Портативний', 'АС1-2/3 Портативний'), ('АС1_23Стаціонар', 'АС1-2/3 Стаціонар'), ('АС1_4ДСК', 'АС1-4 ДСК'), ('АС23_4МОСІ', 'АС23-4 МОСІ Соц і т.п.')], max_length=25, null=True, verbose_name='Тип ЕОТ'),
        ),
        migrations.CreateModel(
            name='OIDProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата початку')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершення')),
                ('status', models.CharField(choices=[('очікує', 'Очікує'), ('виконано', 'Виконано'), ('пропущено', 'Пропущено')], default='очікує', max_length=20, verbose_name='Статус процесу')),
                ('oid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_process', to='oids.oid', verbose_name='ОІД')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oids.processtemplate', verbose_name='Використаний шаблон')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва кроку')),
                ('order', models.PositiveIntegerField(default=10, verbose_name='Порядок виконання')),
                ('trigger_document_status', models.CharField(choices=[('чернетка', 'Чернетка'), ('надіслано на реєстрацію', 'Надіслано на реєстрацію'), ('зареєстровано', 'Зареєстровано'), ('надіслано до в/ч', 'Надіслано до в/ч'), ('завершено', 'Завершено')], default='завершено', max_length=30, verbose_name='Статус документа, що завершує крок')),
                ('responsible_party', models.CharField(choices=[('ми', 'Ми (ГУ)'), ('в/ч', 'Військова частина'), ('дссззі', 'ДССЗЗІ')], max_length=20, verbose_name='Відповідальний за крок')),
                ('description', models.TextField(blank=True, verbose_name='Інструкції до кроку')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oids.documenttype', verbose_name='Тип документа для кроку')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='oids.processtemplate', verbose_name='Шаблон')),
            ],
            options={
                'ordering': ['template', 'order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='OIDProcessStepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('очікує', 'Очікує'), ('виконано', 'Виконано'), ('пропущено', 'Пропущено')], default='очікує', max_length=20, verbose_name='Статус кроку')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата виконання')),
                ('linked_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oids.document', verbose_name='Документ, що виконав крок')),
                ('oid_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_instances', to='oids.oidprocess', verbose_name='Процес ОІД')),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oids.processstep', verbose_name='Крок з шаблону')),
            ],
            options={
                'ordering': ['oid_process', 'process_step__order'],
            },
        ),
    ]
