# Generated by Django 5.2.1 on 2025-06-27 19:58

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0027_processtemplate_document_processing_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oidprocess',
            options={'ordering': ['-id'], 'verbose_name': 'Екземпляр процесу для конкретного ОІД.', 'verbose_name_plural': 'БізнесПроцес: 3. Екземпляри процесів для конкретних ОІД.'},
        ),
        migrations.AlterModelOptions(
            name='oidprocessstepinstance',
            options={'ordering': ['-id'], 'verbose_name': 'Конкретні екземпляри кроків для процесу ОІД.', 'verbose_name_plural': 'БізнесПроцес: 4. Екземпляри кроку для процесу ОІД.'},
        ),
        migrations.AlterModelOptions(
            name='processstep',
            options={'ordering': ['template', 'order'], 'verbose_name': 'Крок у шаблоні процесу', 'verbose_name_plural': 'БізнесПроцес: 2. Кроки у шаблоні процесу'},
        ),
        migrations.AlterModelOptions(
            name='processtemplate',
            options={'ordering': ['-id'], 'verbose_name': 'Шаблон процесу', 'verbose_name_plural': 'БізнесПроцес: 1. Шаблони процесів'},
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='pemin_sub_type',
            field=models.CharField(blank=True, choices=[('МОВНА', 'МОВНА'), ('ВАРМ', 'ВАРМ'), ('ЗАРМ', 'ЗАРМ'), ('АС1-2/3 портативний', 'АС1-2/3 Портативний'), ('АС1-2/3 Стаціонар', 'АС1-2/3 Стаціонар'), ('АС1-4 ДСК', 'АС1-4 ДСК'), ('АС2/3-4 ДСК', 'АС2/3-4 МОСІ Соц і т.п.')], max_length=25, null=True, verbose_name='Тип ЕОТ'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('отримано ТЗ/МЗ', 'Отримано ТЗ/МЗ'), ('ТЗ/МЗ погоджено', 'ТЗ/МЗ Погоджено'), ('отримано заявку', 'Отримано Заявку'), ('отримано АЗР', 'Отримано АЗР'), ('отримано Декларацію', 'Отримано Декларацію'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], default='створюється', max_length=30, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='pemin_sub_type',
            field=models.CharField(blank=True, choices=[('МОВНА', 'МОВНА'), ('ВАРМ', 'ВАРМ'), ('ЗАРМ', 'ЗАРМ'), ('АС1-2/3 портативний', 'АС1-2/3 Портативний'), ('АС1-2/3 Стаціонар', 'АС1-2/3 Стаціонар'), ('АС1-4 ДСК', 'АС1-4 ДСК'), ('АС2/3-4 ДСК', 'АС2/3-4 МОСІ Соц і т.п.')], max_length=25, null=True, verbose_name='Тип ЕОТ'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('отримано ТЗ/МЗ', 'Отримано ТЗ/МЗ'), ('ТЗ/МЗ погоджено', 'ТЗ/МЗ Погоджено'), ('отримано заявку', 'Отримано Заявку'), ('отримано АЗР', 'Отримано АЗР'), ('отримано Декларацію', 'Отримано Декларацію'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], default='створюється', max_length=30, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='responsible_party',
            field=models.CharField(choices=[('ВТЗІ', 'ВТЗІ'), ('ГУ', 'ГУ'), ('в/ч', 'в/ч'), ('ДССЗЗІ', 'ДССЗЗІ')], max_length=20, verbose_name='Відповідальний за крок'),
        ),
        migrations.AlterField(
            model_name='processtemplate',
            name='applies_to_pemin_subtype',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('МОВНА', 'МОВНА'), ('ВАРМ', 'ВАРМ'), ('ЗАРМ', 'ЗАРМ'), ('АС1-2/3 портативний', 'АС1-2/3 Портативний'), ('АС1-2/3 Стаціонар', 'АС1-2/3 Стаціонар'), ('АС1-4 ДСК', 'АС1-4 ДСК'), ('АС2/3-4 ДСК', 'АС2/3-4 МОСІ Соц і т.п.')], max_length=100, null=True, verbose_name='Підтип ПЕМІН'),
        ),
    ]
