# Generated by Django 5.2.1 on 2025-07-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0029_alter_historicaloid_sec_level_alter_oid_sec_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(default='27/14-', max_length=50, verbose_name='Підг. № документа'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='document_number',
            field=models.CharField(default='27/14-', max_length=50, verbose_name='Підг. № документа'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('отримано ТЗ/МЗ', 'Отримано ТЗ/МЗ'), ('ТЗ/МЗ погоджено', 'ТЗ/МЗ Погоджено'), ('отримано заявку', 'Отримано Заявку'), ('атестовано', 'атестовано'), ('отримано АЗР', 'Отримано АЗР'), ('отримано Декларацію', 'Отримано Декларацію'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], default='створюється', max_length=30, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('отримано ТЗ/МЗ', 'Отримано ТЗ/МЗ'), ('ТЗ/МЗ погоджено', 'ТЗ/МЗ Погоджено'), ('отримано заявку', 'Отримано Заявку'), ('атестовано', 'атестовано'), ('отримано АЗР', 'Отримано АЗР'), ('отримано Декларацію', 'Отримано Декларацію'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], default='створюється', max_length=30, verbose_name='Поточний стан ОІД'),
        ),
    ]
