# Generated by Django 5.2.1 on 2025-07-02 18:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0031_alter_historicaloid_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('отримано ТЗ/МЗ', 'Отримано ТЗ/МЗ'), ('очікуємо ТЗ/МЗ(повторно)', 'Очікуємо ТЗ/МЗ(повторно)'), ('ТЗ/МЗ погоджено', 'ТЗ/МЗ Погоджено'), ('отримано заявку', 'Отримано Заявку'), ('атестовано', 'атестовано'), ('АЗР відправлено до ДССЗЗІ', 'АЗР відправлено до ДССЗЗІ'), ('отримано Декларацію', 'Отримано Декларацію'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], default='створюється', max_length=30, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('отримано ТЗ/МЗ', 'Отримано ТЗ/МЗ'), ('очікуємо ТЗ/МЗ(повторно)', 'Очікуємо ТЗ/МЗ(повторно)'), ('ТЗ/МЗ погоджено', 'ТЗ/МЗ Погоджено'), ('отримано заявку', 'Отримано Заявку'), ('атестовано', 'атестовано'), ('АЗР відправлено до ДССЗЗІ', 'АЗР відправлено до ДССЗЗІ'), ('отримано Декларацію', 'Отримано Декларацію'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], default='створюється', max_length=30, verbose_name='Поточний стан ОІД'),
        ),
        migrations.CreateModel(
            name='HistoricalWorkCompletionRegistration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('outgoing_letter_number', models.CharField(max_length=50, verbose_name='Вихідний номер супровідного листа')),
                ('outgoing_letter_date', models.DateField(verbose_name='Дата вихідного супровідного листа')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки до відправки')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.person', verbose_name='Хто створив запис')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Відправка АЗР на реєстрацію',
                'verbose_name_plural': 'historical Відправки АЗР на реєстрацію',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkCompletionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outgoing_letter_number', models.CharField(max_length=50, verbose_name='Вихідний номер супровідного листа')),
                ('outgoing_letter_date', models.DateField(verbose_name='Дата вихідного супровідного листа')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки до відправки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oids.person', verbose_name='Хто створив запис')),
                ('documents', models.ManyToManyField(related_name='completion_registrations', to='oids.document', verbose_name='Документи (АЗР), відправлені на реєстрацію')),
            ],
            options={
                'verbose_name': 'Відправка АЗР на реєстрацію',
                'verbose_name_plural': 'Відправки АЗР на реєстрацію',
                'ordering': ['-outgoing_letter_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalWorkCompletionResponse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('response_letter_number', models.CharField(max_length=50, verbose_name='Номер листа-відповіді від ДССЗЗІ')),
                ('response_letter_date', models.DateField(verbose_name='Дата листа-відповіді')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки до відповіді')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.person', verbose_name='Хто вніс відповідь')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registration_request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.workcompletionregistration', verbose_name='Запит на реєстрацію (відправлений лист)')),
            ],
            options={
                'verbose_name': 'historical Відповідь ДССЗЗІ по АЗР',
                'verbose_name_plural': 'historical Відповіді ДССЗЗІ по АЗР',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkCompletionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_letter_number', models.CharField(max_length=50, verbose_name='Номер листа-відповіді від ДССЗЗІ')),
                ('response_letter_date', models.DateField(verbose_name='Дата листа-відповіді')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки до відповіді')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oids.person', verbose_name='Хто вніс відповідь')),
                ('registration_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_received', to='oids.workcompletionregistration', verbose_name='Запит на реєстрацію (відправлений лист)')),
            ],
            options={
                'verbose_name': 'Відповідь ДССЗЗІ по АЗР',
                'verbose_name_plural': 'Відповіді ДССЗЗІ по АЗР',
            },
        ),
    ]
