# Generated by Django 5.2.1 on 2025-07-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0032_alter_historicaloid_status_alter_oid_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkcompletionregistration',
            old_name='created_by',
            new_name='send_by',
        ),
        migrations.RenameField(
            model_name='historicalworkcompletionresponse',
            old_name='created_at',
            new_name='received_at',
        ),
        migrations.RenameField(
            model_name='historicalworkcompletionresponse',
            old_name='created_by',
            new_name='received_by',
        ),
        migrations.RenameField(
            model_name='workcompletionregistration',
            old_name='created_by',
            new_name='send_by',
        ),
        migrations.RenameField(
            model_name='workcompletionresponse',
            old_name='created_at',
            new_name='received_at',
        ),
        migrations.RenameField(
            model_name='workcompletionresponse',
            old_name='created_by',
            new_name='received_by',
        ),
    ]
