# Generated by Django 5.2.1 on 2025-07-02 19:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0033_rename_created_by_historicalworkcompletionregistration_send_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attestationregistration',
            options={'ordering': ['-outgoing_letter_date', '-id'], 'verbose_name': 'АА відправка на реєстрацію (ДССЗЗІ)', 'verbose_name_plural': 'АА відправки на реєстрацію (ДССЗЗІ)'},
        ),
        migrations.AlterModelOptions(
            name='attestationresponse',
            options={'ordering': ['-response_letter_date', '-id'], 'verbose_name': 'АА відповідь ДССЗЗІ', 'verbose_name_plural': 'АА відповіді ДССЗЗІ'},
        ),
        migrations.AlterModelOptions(
            name='historicalattestationregistration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical АА відправка на реєстрацію (ДССЗЗІ)', 'verbose_name_plural': 'historical АА відправки на реєстрацію (ДССЗЗІ)'},
        ),
        migrations.AlterModelOptions(
            name='historicalattestationresponse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical АА відповідь ДССЗЗІ', 'verbose_name_plural': 'historical АА відповіді ДССЗЗІ'},
        ),
        migrations.AlterModelOptions(
            name='historicalworkcompletionregistration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical АЗР відправка на реєстрацію', 'verbose_name_plural': 'historical АЗР відправки на реєстрацію'},
        ),
        migrations.AlterModelOptions(
            name='historicalworkcompletionresponse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical АЗР відповідь ДССЗЗІ', 'verbose_name_plural': 'historical АЗР відповіді ДССЗЗІ'},
        ),
        migrations.AlterModelOptions(
            name='workcompletionregistration',
            options={'ordering': ['-outgoing_letter_date'], 'verbose_name': 'АЗР відправка на реєстрацію', 'verbose_name_plural': 'АЗР відправки на реєстрацію'},
        ),
        migrations.AlterModelOptions(
            name='workcompletionresponse',
            options={'verbose_name': 'АЗР відповідь ДССЗЗІ', 'verbose_name_plural': 'АЗР відповіді ДССЗЗІ'},
        ),
        migrations.RemoveField(
            model_name='workcompletionregistration',
            name='documents',
        ),
        migrations.CreateModel(
            name='DeclarationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outgoing_letter_number', models.CharField(max_length=50, verbose_name='Вихідний номер супровідного листа')),
                ('outgoing_letter_date', models.DateField(verbose_name='Дата вихідного супровідного листа')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oids.person', verbose_name='Хто створив запис')),
                ('documents', models.ManyToManyField(related_name='declaration_registrations', to='oids.document', verbose_name='Документи (Декларації), відправлені на реєстрацію')),
            ],
            options={
                'verbose_name': 'Декларація відправка на реєстрацію',
                'verbose_name_plural': 'Декларації відправки на реєстрацію',
                'ordering': ['-outgoing_letter_date'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_letter_number', models.CharField(max_length=50, verbose_name='Номер листа-відповіді')),
                ('response_letter_date', models.DateField(verbose_name='Дата листа-відповіді')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oids.person', verbose_name='Хто вніс відповідь')),
                ('registration_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_received', to='oids.declarationregistration', verbose_name='Запит на реєстрацію (відправлений лист)')),
            ],
            options={
                'verbose_name': 'Декларація відповідь ДССЗЗІ',
                'verbose_name_plural': 'Декларації відповіді ДССЗЗІ',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDeclarationRegistration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('outgoing_letter_number', models.CharField(max_length=50, verbose_name='Вихідний номер супровідного листа')),
                ('outgoing_letter_date', models.DateField(verbose_name='Дата вихідного супровідного листа')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.person', verbose_name='Хто створив запис')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Декларація відправка на реєстрацію',
                'verbose_name_plural': 'historical Декларації відправки на реєстрацію',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeclarationResponse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('response_letter_number', models.CharField(max_length=50, verbose_name='Номер листа-відповіді')),
                ('response_letter_date', models.DateField(verbose_name='Дата листа-відповіді')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.person', verbose_name='Хто вніс відповідь')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registration_request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.declarationregistration', verbose_name='Запит на реєстрацію (відправлений лист)')),
            ],
            options={
                'verbose_name': 'historical Декларація відповідь ДССЗЗІ',
                'verbose_name_plural': 'historical Декларації відповіді ДССЗЗІ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
