# Generated by Django 5.2.1 on 2025-07-03 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0034_alter_attestationregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='wcr_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_documents', to='oids.workcompletionregistration', verbose_name='Відправка АЗР на реєстрацію'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='wcr_submission',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.workcompletionregistration', verbose_name='Відправка АЗР на реєстрацію'),
        ),
        migrations.AddField(
            model_name='workcompletionregistration',
            name='oids',
            field=models.ManyToManyField(to='oids.oid', verbose_name='ОІДи, що згадуються у відправці'),
        ),
        migrations.AlterField(
            model_name='declarationregistration',
            name='documents',
            field=models.ManyToManyField(to='oids.document', verbose_name='Документи (Декларації), відправлені на реєстрацію'),
        ),
        migrations.CreateModel(
            name='DskEot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher', models.CharField(max_length=200, verbose_name='Шифр')),
                ('serial_number', models.CharField(max_length=200, verbose_name='Серійний номер')),
                ('inventory_number', models.CharField(max_length=200, verbose_name='Інвентарний номер')),
                ('room', models.CharField(max_length=255, verbose_name='Приміщення')),
                ('security_level', models.CharField(default='ДСК', max_length=50, verbose_name='Гриф')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oids.unit', verbose_name='Військова частина')),
            ],
            options={
                'verbose_name': 'ДСК ЕОТ',
                'verbose_name_plural': 'ДСК ЕОТ',
                'ordering': ['unit', 'cipher'],
            },
        ),
    ]
