# Generated by Django 5.2.1 on 2025-07-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0035_document_wcr_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcompletionregistration',
            name='documents',
            field=models.ManyToManyField(related_name='completion_registrations', to='oids.document', verbose_name='Документи (АЗР), відправлені на реєстрацію'),
        ),
    ]
