# Generated by Django 5.2.1 on 2025-07-05 06:06

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0036_workcompletionregistration_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declarationregistration',
            options={'ordering': ['-outgoing_letter_date'], 'verbose_name': 'Відправка Декларації на реєстрацію', 'verbose_name_plural': 'Відправки Декларацій на реєстрацію'},
        ),
        migrations.AlterModelOptions(
            name='declarationresponse',
            options={'verbose_name': 'Відповідь ДССЗЗІ по Декларації', 'verbose_name_plural': 'Відповіді ДССЗЗІ по Деклараціях'},
        ),
        migrations.AlterModelOptions(
            name='historicaldeclarationregistration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Відправка Декларації на реєстрацію', 'verbose_name_plural': 'historical Відправки Декларацій на реєстрацію'},
        ),
        migrations.AlterModelOptions(
            name='historicaldeclarationresponse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Відповідь ДССЗЗІ по Декларації', 'verbose_name_plural': 'historical Відповіді ДССЗЗІ по Деклараціях'},
        ),
        migrations.RemoveField(
            model_name='declarationregistration',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='declaration_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_documents', to='oids.declarationregistration', verbose_name='Відправка Декларації на реєстрацію'),
        ),
        migrations.AddField(
            model_name='dskeot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dskeot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='declaration_submission',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.declarationregistration', verbose_name='Відправка Декларації на реєстрацію'),
        ),
        migrations.AlterField(
            model_name='declarationregistration',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітки до відправки'),
        ),
        migrations.AlterField(
            model_name='declarationresponse',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітки до відповіді'),
        ),
        migrations.AlterField(
            model_name='document',
            name='process_date',
            field=models.DateField(verbose_name='Дата опрацювання документу (Підг.№ від)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='work_date',
            field=models.DateField(verbose_name='Дата проведення робіт на ОІД'),
        ),
        migrations.AlterField(
            model_name='dskeot',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Інвентарний номер'),
        ),
        migrations.AlterField(
            model_name='dskeot',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='dskeot',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsk_eots', to='oids.unit', verbose_name='Військова частина'),
        ),
        migrations.AlterField(
            model_name='historicaldeclarationregistration',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітки до відправки'),
        ),
        migrations.AlterField(
            model_name='historicaldeclarationresponse',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітки до відповіді'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='process_date',
            field=models.DateField(verbose_name='Дата опрацювання документу (Підг.№ від)'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='work_date',
            field=models.DateField(verbose_name='Дата проведення робіт на ОІД'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Інв. №'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='s/n'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Інв. №'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='s/n'),
        ),
        migrations.CreateModel(
            name='HistoricalDskEot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cipher', models.CharField(max_length=200, verbose_name='Шифр')),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Серійний номер')),
                ('inventory_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Інвентарний номер')),
                ('room', models.CharField(max_length=255, verbose_name='Приміщення')),
                ('security_level', models.CharField(default='ДСК', max_length=50, verbose_name='Гриф')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.unit', verbose_name='Військова частина')),
            ],
            options={
                'verbose_name': 'historical ДСК ЕОТ',
                'verbose_name_plural': 'historical ДСК ЕОТ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
