# Generated by Django 5.2.1 on 2025-07-05 07:52

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0037_alter_declarationregistration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldeclarationresponse',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaldeclarationresponse',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldeclarationresponse',
            name='registration_request',
        ),
        migrations.AlterModelOptions(
            name='declarationregistration',
            options={'ordering': ['-outgoing_letter_date'], 'verbose_name': 'Реєстрація Декларації', 'verbose_name_plural': 'Реєстрації Декларацій'},
        ),
        migrations.AlterModelOptions(
            name='historicaldeclarationregistration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Реєстрація Декларації', 'verbose_name_plural': 'historical Реєстрації Декларацій'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='declaration_submission',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='declaration_submission',
        ),
        migrations.AddField(
            model_name='declarationregistration',
            name='response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата внесення відповіді'),
        ),
        migrations.AddField(
            model_name='declarationregistration',
            name='response_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_declaration_responses', to='oids.person', verbose_name='Хто вніс відповідь'),
        ),
        migrations.AddField(
            model_name='declarationregistration',
            name='response_letter_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата листа-відповіді'),
        ),
        migrations.AddField(
            model_name='declarationregistration',
            name='response_letter_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер листа-відповіді'),
        ),
        migrations.AddField(
            model_name='declarationregistration',
            name='response_note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітки до відповіді'),
        ),
        migrations.AddField(
            model_name='declarationregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicaldeclarationregistration',
            name='response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата внесення відповіді'),
        ),
        migrations.AddField(
            model_name='historicaldeclarationregistration',
            name='response_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.person', verbose_name='Хто вніс відповідь'),
        ),
        migrations.AddField(
            model_name='historicaldeclarationregistration',
            name='response_letter_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата листа-відповіді'),
        ),
        migrations.AddField(
            model_name='historicaldeclarationregistration',
            name='response_letter_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер листа-відповіді'),
        ),
        migrations.AddField(
            model_name='historicaldeclarationregistration',
            name='response_note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітки до відповіді'),
        ),
        migrations.AddField(
            model_name='historicaldeclarationregistration',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='declarationregistration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_declaration_registrations', to='oids.person', verbose_name='Хто створив запис'),
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_number', models.CharField(max_length=50, verbose_name='Підготовлений № Декларації')),
                ('prepared_date', models.DateField(verbose_name='Дата опрацювання Декларації')),
                ('registered_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Зареєстрований № в ДССЗЗІ')),
                ('registered_date', models.DateField(blank=True, null=True, verbose_name='Дата реєстрації в ДССЗЗІ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dsk_eot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='oids.dskeot', verbose_name="Об'єкт ДСК ЕОТ")),
            ],
            options={
                'verbose_name': 'Декларація відповідності',
                'verbose_name_plural': 'Декларації відповідності',
                'ordering': ['-prepared_date'],
            },
        ),
        migrations.AddField(
            model_name='declarationregistration',
            name='declarations',
            field=models.ManyToManyField(related_name='registrations', to='oids.declaration', verbose_name='Декларації у відправці'),
        ),
        migrations.CreateModel(
            name='HistoricalDeclaration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('prepared_number', models.CharField(max_length=50, verbose_name='Підготовлений № Декларації')),
                ('prepared_date', models.DateField(verbose_name='Дата опрацювання Декларації')),
                ('registered_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Зареєстрований № в ДССЗЗІ')),
                ('registered_date', models.DateField(blank=True, null=True, verbose_name='Дата реєстрації в ДССЗЗІ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dsk_eot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.dskeot', verbose_name="Об'єкт ДСК ЕОТ")),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Декларація відповідності',
                'verbose_name_plural': 'historical Декларації відповідності',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='DeclarationResponse',
        ),
        migrations.DeleteModel(
            name='HistoricalDeclarationResponse',
        ),
    ]
