# Generated by Django 5.2.1 on 2025-07-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0038_remove_historicaldeclarationresponse_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attestationregistration',
            options={'ordering': ['-outgoing_letter_date', '-id'], 'verbose_name': 'ДССЗЗІ: АА відправка на реєстрацію', 'verbose_name_plural': 'ДССЗЗІ: АА відправки на реєстрацію'},
        ),
        migrations.AlterModelOptions(
            name='attestationresponse',
            options={'ordering': ['-response_letter_date', '-id'], 'verbose_name': 'ДССЗЗІ: АА відповідь', 'verbose_name_plural': 'ДССЗЗІ: АА відповіді'},
        ),
        migrations.AlterModelOptions(
            name='declaration',
            options={'ordering': ['-prepared_date'], 'verbose_name': 'ДССЗЗІ: Декларація відповідності відправка', 'verbose_name_plural': 'ДССЗЗІ: Декларації відповідності відправка'},
        ),
        migrations.AlterModelOptions(
            name='declarationregistration',
            options={'ordering': ['-outgoing_letter_date'], 'verbose_name': 'ДССЗЗІ: Декларація відповідь', 'verbose_name_plural': 'ДССЗЗІ: Декларація відповіді'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['oid_type', 'work_type', 'name'], 'verbose_name': 'Довідково: Тип документа', 'verbose_name_plural': 'Довідково: Типи документів'},
        ),
        migrations.AlterModelOptions(
            name='dskeot',
            options={'ordering': ['unit', 'cipher'], 'verbose_name': 'ОІД ДСК ЕОТ', 'verbose_name_plural': 'ОІД ДСК ЕОТ'},
        ),
        migrations.AlterModelOptions(
            name='historicalattestationregistration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ДССЗЗІ: АА відправка на реєстрацію', 'verbose_name_plural': 'historical ДССЗЗІ: АА відправки на реєстрацію'},
        ),
        migrations.AlterModelOptions(
            name='historicalattestationresponse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ДССЗЗІ: АА відповідь', 'verbose_name_plural': 'historical ДССЗЗІ: АА відповіді'},
        ),
        migrations.AlterModelOptions(
            name='historicaldeclaration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ДССЗЗІ: Декларація відповідності відправка', 'verbose_name_plural': 'historical ДССЗЗІ: Декларації відповідності відправка'},
        ),
        migrations.AlterModelOptions(
            name='historicaldeclarationregistration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ДССЗЗІ: Декларація відповідь', 'verbose_name_plural': 'historical ДССЗЗІ: Декларація відповіді'},
        ),
        migrations.AlterModelOptions(
            name='historicaldocumenttype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Довідково: Тип документа', 'verbose_name_plural': 'historical Довідково: Типи документів'},
        ),
        migrations.AlterModelOptions(
            name='historicaldskeot',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ОІД ДСК ЕОТ', 'verbose_name_plural': 'historical ОІД ДСК ЕОТ'},
        ),
        migrations.AlterModelOptions(
            name='historicaloidstatuschange',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ДССЗЗІ: Зміна статусу ОІД', 'verbose_name_plural': 'historical ДССЗЗІ: Зміни статусу ОІД'},
        ),
        migrations.AlterModelOptions(
            name='historicalperson',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Довідково: Виконавець', 'verbose_name_plural': 'historical Довідково: Виконавці'},
        ),
        migrations.AlterModelOptions(
            name='historicaltripresultforunit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Опрацювання результат відрядження для частини', 'verbose_name_plural': 'historical Опрацювання результати відрядження для частин'},
        ),
        migrations.AlterModelOptions(
            name='historicalunit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Структура: Військова частина', 'verbose_name_plural': 'historical Структура: Військові частини'},
        ),
        migrations.AlterModelOptions(
            name='historicalworkcompletionregistration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ДССЗЗІ: АЗР відправка на реєстрацію', 'verbose_name_plural': 'historical ДССЗЗІ: АЗР відправки на реєстрацію'},
        ),
        migrations.AlterModelOptions(
            name='historicalworkcompletionresponse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ДССЗЗІ: АЗР відповідь ДССЗЗІ', 'verbose_name_plural': 'historical ДССЗЗІ: АЗР відповіді ДССЗЗІ'},
        ),
        migrations.AlterModelOptions(
            name='historicalworkrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Заявки: Заявка на проведення робіт', 'verbose_name_plural': 'historical Заявки: Заявки на проведення робіт'},
        ),
        migrations.AlterModelOptions(
            name='historicalworkrequestitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Заявки: Елемент заявки', 'verbose_name_plural': 'historical Заявки: Елементи заявки'},
        ),
        migrations.AlterModelOptions(
            name='oidstatuschange',
            options={'ordering': ['-changed_at'], 'verbose_name': 'ДССЗЗІ: Зміна статусу ОІД', 'verbose_name_plural': 'ДССЗЗІ: Зміни статусу ОІД'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Довідково: Виконавець', 'verbose_name_plural': 'Довідково: Виконавці'},
        ),
        migrations.AlterModelOptions(
            name='territorialmanagement',
            options={'verbose_name': 'Структура: Територіальне управління', 'verbose_name_plural': 'Структура: Територіальні управління'},
        ),
        migrations.AlterModelOptions(
            name='tripresultforunit',
            options={'ordering': ['-outgoing_letter_date', '-id'], 'verbose_name': 'Опрацювання результат відрядження для частини', 'verbose_name_plural': 'Опрацювання результати відрядження для частин'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Структура: Військова частина', 'verbose_name_plural': 'Структура: Військові частини'},
        ),
        migrations.AlterModelOptions(
            name='unitgroup',
            options={'verbose_name': 'Структура: Група військових частин (для відряджень)', 'verbose_name_plural': 'Структура: Групи військових частин (для відряджень)'},
        ),
        migrations.AlterModelOptions(
            name='workcompletionregistration',
            options={'ordering': ['-outgoing_letter_date'], 'verbose_name': 'ДССЗЗІ: АЗР відправка на реєстрацію', 'verbose_name_plural': 'ДССЗЗІ: АЗР відправки на реєстрацію'},
        ),
        migrations.AlterModelOptions(
            name='workcompletionresponse',
            options={'verbose_name': 'ДССЗЗІ: АЗР відповідь ДССЗЗІ', 'verbose_name_plural': 'ДССЗЗІ: АЗР відповіді ДССЗЗІ'},
        ),
        migrations.AlterModelOptions(
            name='workrequest',
            options={'verbose_name': 'Заявки: Заявка на проведення робіт', 'verbose_name_plural': 'Заявки: Заявки на проведення робіт'},
        ),
        migrations.AlterModelOptions(
            name='workrequestitem',
            options={'ordering': ['request', 'request__incoming_date'], 'verbose_name': 'Заявки: Елемент заявки', 'verbose_name_plural': 'Заявки: Елементи заявки'},
        ),
        migrations.AlterUniqueTogether(
            name='oid',
            unique_together={('unit', 'cipher')},
        ),
    ]
