# Generated by Django 5.2.1 on 2025-11-18 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0040_alter_historicaloid_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва проєкту')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('group', models.CharField(choices=[('Загальна', 'Загальна'), ('Управління', 'Управління'), ('ЗБСІ', 'ЗБСІ'), ('ІАРМ', 'ІАРМ'), ('СД КТК', 'СД КТК'), ('Майстерня', 'Майстерня'), ('ПДТР', 'ПДТР'), ('СлужбаТЗІ', 'Служба ТЗІ')], default='Загальна', max_length=20, verbose_name='Відділ/Група')),
            ],
            options={
                'verbose_name': 'Проєкт',
                'verbose_name_plural': 'Проєкти',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва статусу')),
                ('color', models.CharField(default='#d1d5db', max_length=20, verbose_name='Колір (HEX або назва)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Стандартний')),
            ],
            options={
                'verbose_name': 'Статус завдання',
                'verbose_name_plural': 'Статуси завдання',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Термін виконання')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Виконано')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата виконання')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
            },
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='history_user',
        ),
        migrations.AlterModelOptions(
            name='historicalworkrequestitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Заявки: Елемент заявки (ОІД)', 'verbose_name_plural': 'historical Заявки: Елементи заявки (ОІД)'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['full_name'], 'verbose_name': 'Виконавець', 'verbose_name_plural': 'Довідково: Виконавці'},
        ),
        migrations.AlterModelOptions(
            name='workrequestitem',
            options={'ordering': ['request', 'request__incoming_date'], 'verbose_name': 'Заявки: Елемент заявки (ОІД)', 'verbose_name_plural': 'Заявки: Елементи заявки (ОІД)'},
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.CharField(choices=[('Загальна', 'Загальна'), ('Управління', 'Управління'), ('ЗБСІ', 'ЗБСІ'), ('ІАРМ', 'ІАРМ'), ('СД КТК', 'СД КТК'), ('Майстерня', 'Майстерня'), ('ПДТР', 'ПДТР'), ('СлужбаТЗІ', 'Служба ТЗІ')], default='Управління', help_text='Підрозділ, до якого належить працівник', max_length=20, verbose_name='Підрозділ'),
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, help_text='Прізвище окремо (опціонально)', max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('отримано ТЗ/МЗ', 'Отримано ТЗ/МЗ'), ('очікуємо ТЗ/МЗ(повторно)', 'Очікуємо ТЗ/МЗ(повторно)'), ('ТЗ/МЗ погоджено', 'ТЗ/МЗ Погоджено'), ('отримано заявку', 'Отримано Заявку уточнити'), ('отримано заявку ІК', 'Отримано Заявку ІК'), ('отримано заявку Первинна Атестація', 'Отримано Заявку Первинна Атестація'), ('отримано заявку Чергова Атестація', 'Отримано Заявку Чергова Атестація'), ('атестовано', 'атестовано'), ('АЗР відправлено до ДССЗЗІ', 'АЗР відправлено до ДССЗЗІ'), ('отримано Декларацію', 'Отримано Декларацію'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], default='створюється', max_length=35, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('отримано ТЗ/МЗ', 'Отримано ТЗ/МЗ'), ('очікуємо ТЗ/МЗ(повторно)', 'Очікуємо ТЗ/МЗ(повторно)'), ('ТЗ/МЗ погоджено', 'ТЗ/МЗ Погоджено'), ('отримано заявку', 'Отримано Заявку уточнити'), ('отримано заявку ІК', 'Отримано Заявку ІК'), ('отримано заявку Первинна Атестація', 'Отримано Заявку Первинна Атестація'), ('отримано заявку Чергова Атестація', 'Отримано Заявку Чергова Атестація'), ('атестовано', 'атестовано'), ('АЗР відправлено до ДССЗЗІ', 'АЗР відправлено до ДССЗЗІ'), ('отримано Декларацію', 'Отримано Декларацію'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], default='створюється', max_length=35, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(help_text="Введіть прізвище та ім'я працівника", max_length=255, verbose_name="Прізвище, ім'я"),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Чи активний працівник', verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(help_text='Посада працівника', max_length=255, verbose_name='Посада'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['group', 'is_active'], name='oids_person_group_ee3d35_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['full_name'], name='oids_person_full_na_44bfb2_idx'),
        ),
        migrations.AddField(
            model_name='status',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_statuses', to='oids.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='oids.person', verbose_name='Виконавець'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='oids.person', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='oids.project', verbose_name='Проєкт'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='oids.status', verbose_name='Поточний статус'),
        ),
        migrations.DeleteModel(
            name='HistoricalPerson',
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('name', 'project')},
        ),
    ]
