# Generated by Django 5.2.7 on 2025-11-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0042_person_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaloid',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': "historical Об'єкт інформаційної діяльності (ОІД)", 'verbose_name_plural': "historical Об'єкти інформаційної діяльності (ОІД)"},
        ),
        migrations.AlterModelOptions(
            name='oid',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_oid', 'Може затверджувати ОІД'), ('can_archive_oid', 'Може архівувати ОІД')], 'verbose_name': "Об'єкт інформаційної діяльності (ОІД)", 'verbose_name_plural': "Об'єкти інформаційної діяльності (ОІД)"},
        ),
        migrations.AddField(
            model_name='historicaloid',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Чи використовується ОІД наразі', verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='oid',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Чи використовується ОІД наразі', verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='cipher',
            field=models.CharField(db_index=True, help_text='Унікальний шифр в межах частини', max_length=100, verbose_name='Шифр ОІД'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Дата створення ОІД'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='full_name',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='Повна назва ОІД'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Інвентарний №'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='oid_type',
            field=models.CharField(choices=[('ПЕМІН', 'ПЕМІН'), ('МОВНА', 'МОВНА')], db_index=True, help_text="Оберіть тип об'єкта: МОВНА або ПЕМІН", max_length=10, verbose_name='Тип ОІД'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='pemin_sub_type',
            field=models.CharField(blank=True, choices=[('МОВНА', 'МОВНА'), ('ВАРМ', 'ВАРМ'), ('ЗАРМ', 'ЗАРМ'), ('АС1-2/3 портативний', 'АС1-2/3 Портативний'), ('АС1-2/3 Стаціонар', 'АС1-2/3 Стаціонар'), ('АС1-4 ДСК', 'АС1-4 ДСК'), ('АС2/3-4 ДСК', 'АС2/3-4 МОСІ Соц і т.п.')], help_text='Тільки для ПЕМІН типу', max_length=25, null=True, verbose_name='Тип ЕОТ'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='room',
            field=models.CharField(help_text='Номер приміщення де розташований ОІД', max_length=255, verbose_name='Приміщення №'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='sec_level',
            field=models.CharField(choices=[('Таємно', 'Таємно'), ('Цілком таємно', 'Цілком таємно'), ('уточнити', 'уточнити'), ('ДСК', 'ДСК')], db_index=True, max_length=15, verbose_name='Гриф'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('отримано ТЗ/МЗ', 'Отримано ТЗ/МЗ'), ('очікуємо ТЗ/МЗ(повторно)', 'Очікуємо ТЗ/МЗ(повторно)'), ('ТЗ/МЗ погоджено', 'ТЗ/МЗ Погоджено'), ('отримано заявку', 'Отримано Заявку уточнити'), ('отримано заявку ІК', 'Отримано Заявку ІК'), ('отримано заявку Первинна Атестація', 'Отримано Заявку Первинна Атестація'), ('отримано заявку Чергова Атестація', 'Отримано Заявку Чергова Атестація'), ('атестовано', 'атестовано'), ('АЗР відправлено до ДССЗЗІ', 'АЗР відправлено до ДССЗЗІ'), ('отримано Декларацію', 'Отримано Декларацію'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], db_index=True, default='створюється', max_length=35, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='cipher',
            field=models.CharField(db_index=True, help_text='Унікальний шифр в межах частини', max_length=100, verbose_name='Шифр ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата створення ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Повна назва ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Інвентарний №'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='oid_type',
            field=models.CharField(choices=[('ПЕМІН', 'ПЕМІН'), ('МОВНА', 'МОВНА')], db_index=True, help_text="Оберіть тип об'єкта: МОВНА або ПЕМІН", max_length=10, verbose_name='Тип ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='pemin_sub_type',
            field=models.CharField(blank=True, choices=[('МОВНА', 'МОВНА'), ('ВАРМ', 'ВАРМ'), ('ЗАРМ', 'ЗАРМ'), ('АС1-2/3 портативний', 'АС1-2/3 Портативний'), ('АС1-2/3 Стаціонар', 'АС1-2/3 Стаціонар'), ('АС1-4 ДСК', 'АС1-4 ДСК'), ('АС2/3-4 ДСК', 'АС2/3-4 МОСІ Соц і т.п.')], help_text='Тільки для ПЕМІН типу', max_length=25, null=True, verbose_name='Тип ЕОТ'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='room',
            field=models.CharField(help_text='Номер приміщення де розташований ОІД', max_length=255, verbose_name='Приміщення №'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='sec_level',
            field=models.CharField(choices=[('Таємно', 'Таємно'), ('Цілком таємно', 'Цілком таємно'), ('уточнити', 'уточнити'), ('ДСК', 'ДСК')], db_index=True, max_length=15, verbose_name='Гриф'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='status',
            field=models.CharField(choices=[('створюється', 'Створюється'), ('отримано ТЗ/МЗ', 'Отримано ТЗ/МЗ'), ('очікуємо ТЗ/МЗ(повторно)', 'Очікуємо ТЗ/МЗ(повторно)'), ('ТЗ/МЗ погоджено', 'ТЗ/МЗ Погоджено'), ('отримано заявку', 'Отримано Заявку уточнити'), ('отримано заявку ІК', 'Отримано Заявку ІК'), ('отримано заявку Первинна Атестація', 'Отримано Заявку Первинна Атестація'), ('отримано заявку Чергова Атестація', 'Отримано Заявку Чергова Атестація'), ('атестовано', 'атестовано'), ('АЗР відправлено до ДССЗЗІ', 'АЗР відправлено до ДССЗЗІ'), ('отримано Декларацію', 'Отримано Декларацію'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], db_index=True, default='створюється', max_length=35, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oids', to='oids.unit', verbose_name='Військова частина'),
        ),
        migrations.AddIndex(
            model_name='oid',
            index=models.Index(fields=['unit', 'status'], name='oids_oid_unit_id_618d63_idx'),
        ),
        migrations.AddIndex(
            model_name='oid',
            index=models.Index(fields=['oid_type', 'is_active'], name='oids_oid_oid_typ_0d0e00_idx'),
        ),
        migrations.AddIndex(
            model_name='oid',
            index=models.Index(fields=['-created_at'], name='oids_oid_created_5401c5_idx'),
        ),
    ]
