# Generated by Django 5.2.7 on 2025-11-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0043_alter_historicaloid_options_alter_oid_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalworkrequestitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical work request item', 'verbose_name_plural': 'historical work request items'},
        ),
        migrations.AlterModelOptions(
            name='workrequestitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='workrequestitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='trip_result_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_documents_direct', to='oids.tripresultforunit', verbose_name='Відправка результатів у в/ч'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='trip_result_sent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.tripresultforunit', verbose_name='Відправка результатів у в/ч'),
        ),
        migrations.AlterField(
            model_name='document',
            name='attestation_registration_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_documents', to='oids.attestationregistration', verbose_name='Відправка на реєстрацію (атестація)'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='attestation_registration_sent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oids.attestationregistration', verbose_name='Відправка на реєстрацію (атестація)'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Інвентарний №'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='status',
            field=models.CharField(choices=[('неактивний', 'Неактивний'), ('створюється', 'Створюється'), ('отримано ТЗ/МЗ', 'Отримано ТЗ/МЗ'), ('очікуємо ТЗ/МЗ(повторно)', 'Очікуємо ТЗ/МЗ(повторно)'), ('ТЗ/МЗ погоджено', 'ТЗ/МЗ Погоджено'), ('отримано заявку', 'Отримано Заявку уточнити'), ('отримано заявку ІК', 'Отримано Заявку ІК'), ('отримано заявку Первинна Атестація', 'Отримано Заявку Первинна Атестація'), ('отримано заявку Чергова Атестація', 'Отримано Заявку Чергова Атестація'), ('атестовано', 'атестовано'), ('АЗР відправлено до ДССЗЗІ', 'АЗР відправлено до ДССЗЗІ'), ('отримано Декларацію', 'Отримано Декларацію'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], db_index=True, max_length=35, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='historicalworkrequest',
            name='status',
            field=models.CharField(choices=[('очікує', 'Очікує'), ('в роботі', 'В роботі'), ('готово до відправки в ДССЗЗІ', 'готово до відправки в ДССЗЗІ'), ('готово до відправки в в/ч', 'готово до відправки в в/ч'), ('на реєстрації в ДССЗЗІ', 'на реєстрації в ДССЗЗІ'), ('виконано', 'Виконано'), ('скасовано', 'Скасовано')], default='очікує', max_length=30, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='historicalworkrequestitem',
            name='status',
            field=models.CharField(choices=[('очікує', 'Очікує'), ('в роботі', 'В роботі'), ('готово до відправки в ДССЗЗІ', 'готово до відправки в ДССЗЗІ'), ('готово до відправки в в/ч', 'готово до відправки в в/ч'), ('на реєстрації в ДССЗЗІ', 'на реєстрації в ДССЗЗІ'), ('виконано', 'Виконано'), ('скасовано', 'Скасовано')], default='очікує', max_length=30, verbose_name='Статус опрацювання ОІД в заявці'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Інвентарний №'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='status',
            field=models.CharField(choices=[('неактивний', 'Неактивний'), ('створюється', 'Створюється'), ('отримано ТЗ/МЗ', 'Отримано ТЗ/МЗ'), ('очікуємо ТЗ/МЗ(повторно)', 'Очікуємо ТЗ/МЗ(повторно)'), ('ТЗ/МЗ погоджено', 'ТЗ/МЗ Погоджено'), ('отримано заявку', 'Отримано Заявку уточнити'), ('отримано заявку ІК', 'Отримано Заявку ІК'), ('отримано заявку Первинна Атестація', 'Отримано Заявку Первинна Атестація'), ('отримано заявку Чергова Атестація', 'Отримано Заявку Чергова Атестація'), ('атестовано', 'атестовано'), ('АЗР відправлено до ДССЗЗІ', 'АЗР відправлено до ДССЗЗІ'), ('отримано Декларацію', 'Отримано Декларацію'), ('активний', 'Активний (В дії)'), ('призупинено', 'Призупинено'), ('скасований', 'Скасований')], db_index=True, max_length=35, verbose_name='Поточний стан ОІД'),
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.CharField(choices=[('Загальна', 'Загальна'), ('Управління', 'Управління'), ('ЗБСІ', 'ЗБСІ'), ('ІАРМ', 'ІАРМ'), ('СД КТК', 'СД КТК'), ('Майстерня', 'Майстерня'), ('ПДТР', 'ПДТР'), ('Аудит З ТЗІ', 'Аудит З ТЗІ'), ('СлужбаТЗІ', 'Служба ТЗІ')], default='Управління', help_text='Підрозділ, до якого належить працівник', max_length=20, verbose_name='Підрозділ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.CharField(choices=[('Загальна', 'Загальна'), ('Управління', 'Управління'), ('ЗБСІ', 'ЗБСІ'), ('ІАРМ', 'ІАРМ'), ('СД КТК', 'СД КТК'), ('Майстерня', 'Майстерня'), ('ПДТР', 'ПДТР'), ('Аудит З ТЗІ', 'Аудит З ТЗІ'), ('СлужбаТЗІ', 'Служба ТЗІ')], default='Загальна', max_length=20, verbose_name='Відділ/Група'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='status',
            field=models.CharField(choices=[('очікує', 'Очікує'), ('в роботі', 'В роботі'), ('готово до відправки в ДССЗЗІ', 'готово до відправки в ДССЗЗІ'), ('готово до відправки в в/ч', 'готово до відправки в в/ч'), ('на реєстрації в ДССЗЗІ', 'на реєстрації в ДССЗЗІ'), ('виконано', 'Виконано'), ('скасовано', 'Скасовано')], default='очікує', max_length=30, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='workrequestitem',
            name='status',
            field=models.CharField(choices=[('очікує', 'Очікує'), ('в роботі', 'В роботі'), ('готово до відправки в ДССЗЗІ', 'готово до відправки в ДССЗЗІ'), ('готово до відправки в в/ч', 'готово до відправки в в/ч'), ('на реєстрації в ДССЗЗІ', 'на реєстрації в ДССЗЗІ'), ('виконано', 'Виконано'), ('скасовано', 'Скасовано')], default='очікує', max_length=30, verbose_name='Статус опрацювання ОІД в заявці'),
        ),
    ]
