# Generated by Django 5.2.7 on 2025-11-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0044_alter_historicalworkrequestitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalworkrequestitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Заявки: Елемент заявки (ОІД)', 'verbose_name_plural': 'historical Заявки: Елементи заявки (ОІД)'},
        ),
        migrations.AlterModelOptions(
            name='workrequestitem',
            options={'ordering': ['request', 'request__incoming_date'], 'verbose_name': 'Заявки: Елемент заявки (ОІД)', 'verbose_name_plural': 'Заявки: Елементи заявки (ОІД)'},
        ),
        migrations.AlterField(
            model_name='tripresultforunit',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='sent_in_trip_results', to='oids.document', verbose_name='Документи до відправки'),
        ),
        migrations.AlterUniqueTogether(
            name='workrequestitem',
            unique_together={('request', 'oid', 'work_type')},
        ),
    ]
