# Generated by Django 5.2.7 on 2025-11-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0045_alter_historicalworkrequestitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalworkrequestitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical work request item', 'verbose_name_plural': 'historical work request items'},
        ),
        migrations.AlterModelOptions(
            name='workrequestitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='workrequestitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='historicaloid',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Серійний номер'),
        ),
    ]
