# Generated by Django 5.2.7 on 2025-11-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0047_remove_document_trip_result_sent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['-is_active', 'sort_order', 'work_type', 'oid_type', 'name'], 'verbose_name': 'Довідково: Тип документа', 'verbose_name_plural': 'Довідково: Типи документів'},
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Менше число виводиться раніше (0, 1, 2...)', verbose_name='Порядок сортування'),
        ),
        migrations.AddField(
            model_name='historicaldocumenttype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='historicaldocumenttype',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Менше число виводиться раніше (0, 1, 2...)', verbose_name='Порядок сортування'),
        ),
    ]
